/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.33
 * Generated at: 2019-02-24 04:59:51 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/standard.jar", Long.valueOf(1491182579116L));
    _jspx_dependants.put("jar:file:/C:/Users/12611/OneDrive/code/eclipse_jee/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/sydsNew6/WEB-INF/lib/standard.jar!/META-INF/c.tld", Long.valueOf(1098682290000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fstep_005fend_005fbegin;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fstep_005fend_005fbegin = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fstep_005fend_005fbegin.release();
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html> <html> \r\n");
      out.write("<head>\r\n");
      out.write("  <meta charset=\"utf-8\">\r\n");
      out.write("  <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge,chrome=1\">\r\n");
      out.write("  <title>第五届“和谐校园”摄影大赛平台</title> \r\n");
      out.write("<!--   <meta name=\"description\" content=\"\"> \r\n");
      out.write("  <meta name=\"keywords\" content=\"\"> --> \r\n");
      out.write("  <script type=\"text/javascript\" src=\"js/jquery-1.11.1.min.js\"></script>\r\n");
      out.write("  <script type=\"text/javascript\" src=\"js/bootstrap.min.js\"></script> \r\n");
      out.write("  <link rel=\"stylesheet\" type=\"text/css\" href=\"css/bootstrap.min.css\">\r\n");
      out.write("  <link rel=\"stylesheet\" type=\"text/css\" href=\"css/carousel.css\">\r\n");
      out.write("  <script type=\"text/javascript\" src=\"js/carousel.js\"></script> \r\n");
      out.write("  <link rel=\"stylesheet\" type=\"text/css\" href=\"css/index.css\">\r\n");
      out.write("  <link rel=\"stylesheet\" type=\"text/css\" href=\"css/style.css\">\r\n");
      out.write("  <!-- 登录注册弹出窗口 -->\r\n");
      out.write("  <link rel=\"stylesheet\" type=\"text/css\" href=\"css/tanchuchuangkou.css\"/>\r\n");
      out.write("  <link rel=\"stylesheet\" type=\"text/css\" href=\"css/index.css\">\r\n");
      out.write("  <script src=\"js/tanchuchuangkou.js\" type=\"text/javascript\" charset=\"utf-8\"></script>\r\n");
      out.write("  <script src=\"js/jquery-1.9.0.min.js\" type=\"text/javascript\" charset=\"utf-8\"></script>   \r\n");
      out.write("  <script src=\"js/jQuery-placeholder.js\" type=\"text/javascript\" charset=\"utf-8\"></script>\r\n");
      out.write("  \r\n");
      out.write("  <script src=\"js/style.js\" type=\"text/javascript\" charset=\"utf-8\"></script> \r\n");
      out.write("<script src=\"js/loginAndRegiste.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("function praise(index) {\r\n");
      out.write(" \t\r\n");
      out.write("    var album_id = $(\"#\"+index).attr(\"id\");\r\n");
      out.write("    var isPraise = false;\r\n");
      out.write("    \r\n");
      out.write("    if ($(\"#praise\"+index).attr(\"src\") != \"images/dianzan1.png\" ){\r\n");
      out.write("\t\t   isPraise = true;\r\n");
      out.write("\t\t   $(\"#praise\"+index).attr(\"src\",\"images/dianzan1.png\") ;\r\n");
      out.write("\t   }else{\r\n");
      out.write("\t\t   isPraise = false;\r\n");
      out.write("\t\t   $(\"#praise\"+index).attr(\"src\",\"images/like.png\") ;\r\n");
      out.write("\t   }\r\n");
      out.write("       var params = {\"album_id\":album_id, \"isPraise\":isPraise};\r\n");
      out.write("\t   $.ajax({\r\n");
      out.write("\t\t   \r\n");
      out.write("\t\t\t\"url\":\"");
      if (_jspx_meth_c_005furl_005f0(_jspx_page_context))
        return;
      out.write("?method=praiseAlbum\",\r\n");
      out.write("\t\t\t\"data\":params,\r\n");
      out.write("\t\t\t\"type\":\"POST\",\r\n");
      out.write("\t\t\t\"success\":function(data){\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\t\"error\":function(){\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\t\"dataType\":\"json\"\r\n");
      out.write("\t\t});\r\n");
      out.write("    \r\n");
      out.write(" }\r\n");
      out.write("\r\n");
      out.write("//搜索\r\n");
      out.write("$(document).ready(function() {\r\n");
      out.write("\t\r\n");
      out.write("\t$('#search_id').bind('click', function() {\r\n");
      out.write("\t\t\t\tsearchStr = $(\"#searchStr\").val();\r\n");
      out.write("\t\t\t\tif (searchStr == \"\") {\r\n");
      out.write("\t\t\t\t\talert(\"请输入关键词\");\r\n");
      out.write("\t\t\t\t\treturn;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\twindow.location=\"GetAlbumsByPage?condition=\"+searchStr;\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\r\n");
      out.write("\t$('#searchStr').bind('keydown', function(e) {\r\n");
      out.write("\t      if (e.keyCode == 13) {\r\n");
      out.write("\t      \tsearchStr = $(\"#searchStr\").val();\r\n");
      out.write("\t  \t\tif (searchStr == \"\") {\r\n");
      out.write("\t  \t\t\talert(\"请输入关键词\");\r\n");
      out.write("\t  \t\t\treturn;\r\n");
      out.write("\t  \t\t}\r\n");
      out.write("\t  \t\twindow.location=\"GetAlbumsByPage?condition=\"+searchStr;\r\n");
      out.write("\t      }\r\n");
      out.write("\t  });\r\n");
      out.write("\t});\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("   </head> \r\n");
      out.write("   <body> \r\n");
      out.write("  \r\n");
      out.write(" <div class=\"header\">\r\n");
      out.write("   <img src=\"img/title.jpg\" style=\"width: 100%;height: auto;\">\r\n");
      out.write(" </div>\r\n");
      out.write("<!--  导航栏 -->\r\n");
      out.write("<nav class=\"nav navbar-inverse\" role=\"navgation\"> \r\n");
      out.write(" <div class=\"container-fluid\"> \r\n");
      out.write(" <div class=\"navbar-header\">\r\n");
      out.write("  <a href=\"#\" class=\"navbar-brand\"></a>\r\n");
      out.write("   <button class=\"navbar-toggle\" data-toggle=\"collapse\" data-target=\".navbar-collapse\"> \r\n");
      out.write("      <span class=\"icon-bar\"></span>\r\n");
      out.write("      <span class=\"icon-bar\"></span> \r\n");
      out.write("      <span class=\"icon-bar\"></span> \r\n");
      out.write("   </button>\r\n");
      out.write("    </div> \r\n");
      out.write("    <div class=\"collapse navbar-collapse\"> \r\n");
      out.write("    <ul class=\"navbar-nav nav\"> \r\n");
      out.write("    <li class=\"active\"><a href=\"index0.jsp\">首页</a></li> \r\n");
      out.write("    <li><a href=\"introduction.jsp\">大赛简介</a></li> \r\n");
      out.write("    <li><a href=\"");
      if (_jspx_meth_c_005furl_005f1(_jspx_page_context))
        return;
      out.write("?method=queryAlbum\">个人中心</a></li>\r\n");
      out.write("     </ul>\r\n");
      out.write("      <div class=\"navbar-form navbar-right\" style=\"margin-right: 30px;\"> \r\n");
      out.write("      <input type=\"text\" class=\"form-control\" name=\"\" id=\"searchStr\" placeholder=\"请输入搜索内容\"> \r\n");
      out.write("      <button class=\"btn btn-success\" style=\"margin-right: 30px;\" id = \"search_id\">搜索</button>\r\n");
      out.write("       <a class=\"navbar-link\" javascript:void(0) id = \"register_id\" onClick=\"showBox1()\">注册</a> \r\n");
      out.write("       <a class=\"navbar-link\" javascript:void(0) id = \"login_id\" onClick=\"showBox()\">登录 </a> \r\n");
      out.write("       <a class=\"navbar-link\" id = \"showUserName\" >");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.user.userName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</a>\r\n");
      out.write("       <a class=\"navbar-link\" type = \"hidden\" style=\"cursor:pointer\" id = \"quit\">退出</a>\r\n");
      out.write("       </div> \r\n");
      out.write("       </div>\r\n");
      out.write("        </div> \r\n");
      out.write("        </nav>\r\n");
      out.write("    <!-- 轮播 -->     \r\n");
      out.write(" <div id=\"container\">\r\n");
      out.write("    <div id=\"list\" style=\"left: 0px;\">\r\n");
      out.write("        <img src=\"images/carsouel11.jpg\" alt=\"1\"/>\r\n");
      out.write("        <img src=\"images/carsouel22.jpg\" alt=\"2\"/>\r\n");
      out.write("        <img src=\"images/carsouel33.jpg\" alt=\"3\"/>\r\n");
      out.write("        <img src=\"images/carsouel44.jpg\" alt=\"4\"/>\r\n");
      out.write("        <img src=\"images/carsouel33.jpg\" alt=\"5\"/>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div id=\"buttons\">\r\n");
      out.write("        <span index=\"1\" class=\"on\"></span> <!--  buttons[0] -->\r\n");
      out.write("        <span index=\"2\"></span>\r\n");
      out.write("        <span index=\"3\"></span>\r\n");
      out.write("        <span index=\"4\"></span>\r\n");
      out.write("        <span index=\"5\"></span>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div id=\"prev\" class=\"arrow\">&lt;</div>\r\n");
      out.write("    <div id=\"next\" class=\"arrow\">&gt;</div>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- 登录注册弹出窗口 -->\r\n");
      out.write("<!-- 注册窗口 -->\r\n");
      out.write("<div class=\"event\" id=\"register_box\" style=\"display: none;\">\r\n");
      out.write("    <div class=\"register\">\r\n");
      out.write("      <div class=\"title\">\r\n");
      out.write("        <img class=\"t_txt\" src=\"images/logo.png\" style=\"width: 200px;height:45px; \">\r\n");
      out.write("        <span class=\"del\" onClick=\"deleteRegister()\">X</span>\r\n");
      out.write("      </div>\r\n");
      out.write("    <form  id=\"\" action=\"\" method=\"post\" name=\"form1\" class=\"FRL\">\r\n");
      out.write("                <input  placeholder=\"请输入用户名\" name=\"userName\" type=\"text\" id=\"userName\" >\r\n");
      out.write("               <input  placeholder=\"请输入密码\" name=\"password\" type=\"password\" id=\"password\">\r\n");
      out.write("               <input  placeholder=\"请确认密码\" name=\"passwordAgain\" type=\"password\" id=\"passwordAgain\" >\r\n");
      out.write("               <select name=\"department\" onChange=\"getDeparment()\" id=\"department\">\r\n");
      out.write("                  <option value=\"0\">请选择参赛组织</option>\r\n");
      out.write("                  <option value=\"职能部门\">职能部门</option>\r\n");
      out.write("                  <option value=\"学院\">学院</option>\r\n");
      out.write("               </select>\r\n");
      out.write("               <select name=\"academy\" id=\"academy\">\r\n");
      out.write("               <option value=\"0\">请选择参赛单位</option>\r\n");
      out.write("               </select>\r\n");
      out.write("             \r\n");
      out.write("               <input type=\"text\" name=\"realName\" id=\"realName\"  value=\"\" placeholder=\"姓名\"/>\r\n");
      out.write("               <input type=\"text\" name=\"cellnumber\" id=\"cellnumber\"  placeholder=\"联系方式\" />\r\n");
      out.write("               <input type=\"submit\" name=\"tregister\" id=\"tregister\" onclick=\"checkCellNumber()\" value=\"注册\" class=\"btnR\" style=\"color: #ffffff;\" />\r\n");
      out.write("             <div><a class=\"RL\" javascript:void(0) onClick=\"showBox2()\">已有账号？去登录</a>\r\n");
      out.write("             </div>\r\n");
      out.write("     </form> \r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("  <div class=\"bg_color\" onClick=\"deleteRegister()\" id=\"bg_filter\" style=\"display: none;\"></div>\r\n");
      out.write("<!-- 登录弹出窗口 -->\r\n");
      out.write("<div class=\"event\" id=\"login_box\" style=\"display: none;\">\r\n");
      out.write("    <div class=\"login\">\r\n");
      out.write("      <div class=\"title\">\r\n");
      out.write("        <img class=\"t_txt\" src=\"images/logo.png\" style=\"width: 200px;height:45px; \">\r\n");
      out.write("        <span class=\"del\" onClick=\"deleteLogin()\">X</span>\r\n");
      out.write("      </div>\r\n");
      out.write("      <form action=\"\" method=\"post\"  class=\"FRL\">\r\n");
      out.write("        <input type=\"text\" name=\"userName\" id=\"userName1\" value=\"\" placeholder=\"请输入用户名\"/>\r\n");
      out.write("        <input type=\"password\" name=\"\" id=\"password1\" value=\"\" placeholder=\"请输入密码\"/>\r\n");
      out.write("        <input type=\"button\" name=\"password\"  id = \"login\" value=\"登录\" class=\"btnR\" style=\"color: #ffffff;\" />    \r\n");
      out.write("        <div><a class=\"RL\"  javascript:void(0) onClick=\"showBox3()\">还没有账号？去注册</a></div>\r\n");
      out.write("      </form> \r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("  <div class=\"bg_color\" onClick=\"deleteLogin()\" id=\"bg_filter\" style=\"display: none;\"></div>\r\n");
      out.write("\r\n");
      out.write("<!-- 图片展示部分 -->\r\n");
      out.write(" <div id=\"container2\">\r\n");
      out.write(" \r\n");
      out.write("    <div class=\"picContent\">\r\n");
      out.write("<div class=\"imgs\" id=\"div_albums\">\r\n");
      out.write("\t\t\t\t");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("    \r\n");
      out.write("      <div id=\"fade\" class=\"black_overlay\"></div>\r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("\r\n");
      out.write("    <!-- 相册里的照片 -->\r\n");
      out.write("\t\t\t<div id=\"editForm\" class=\"white_content\">\r\n");
      out.write("\t\t\t\t<div class=\"imgs\" id=\"div_imgs\"></div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"photo-mask\"></div>\r\n");
      out.write("    <div class=\"photo-panel\">\r\n");
      out.write("      <div class=\"photo-div\">\r\n");
      out.write("        <div class=\"photo-left\">\r\n");
      out.write("          <div class=\"arrow-prv\"></div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"photo-img\">\r\n");
      out.write("          <div class=\"photo-bar\">\r\n");
      out.write("            <div class=\"photo-close\"></div>\r\n");
      out.write("          </div>\r\n");
      out.write("            \r\n");
      out.write("          <div class=\"photo-view-h\">\r\n");
      out.write("\t\t     <img id=\"image_first\" src=\"\" />\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("              \r\n");
      out.write("        <div class=\"photo-right\">\r\n");
      out.write("          <div class=\"arrow-next\"></div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write(" \r\n");
      out.write("  <script src=\"js/jquery.min.js\"></script>\r\n");
      out.write("  <script>\r\n");
      out.write("    var img_index = 0;\r\n");
      out.write("    var img_src = \"\";\r\n");
      out.write("    var num=0;\r\n");
      out.write(" //  for(var i=0;i<4;i++){\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    $(function() {\r\n");
      out.write("\t\t//计算居中位置\r\n");
      out.write("\t\tvar mg_top = ((parseInt($(window).height()) - parseInt($(\r\n");
      out.write("\t\t\t\t\".photo-div\").height())) / 2);\r\n");
      out.write("\r\n");
      out.write("\t\t$(\".photo-div\").css({\r\n");
      out.write("\t\t\t\"margin-top\" : \"\" + mg_top + \"px\"\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t//关闭\r\n");
      out.write("\t\t$(\".photo-close\").click(function() {\r\n");
      out.write("\t\t\t$(\".photo-mask\").hide();\r\n");
      out.write("\t\t\t$(\".photo-panel\").hide();\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t//下一张\r\n");
      out.write("\t\t$(\".photo-panel .photo-div .arrow-next\")\r\n");
      out.write("\t\t\t\t.click(\r\n");
      out.write("\t\t\t\t\t\tfunction() {\r\n");
      out.write("\t\t\t\t\t\t\tif (img_index == -1) {\r\n");
      out.write("\t\t\t\t\t\t\t\timg_index = 1;\r\n");
      out.write("\t\t\t\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t\t\t\timg_index++;\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\tif (img_index >= $(\"#editForm .imgs .album img\").length) {\r\n");
      out.write("\t\t\t\t\t\t\t\timg_index = 0;\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\timg_src = $(\"#editForm .imgs .album img\").eq(\r\n");
      out.write("\t\t\t\t\t\t\t\t\timg_index).attr(\"src\");\r\n");
      out.write("\t\t\t\t\t\t\tphotoView($(\"#editForm .imgs .album img\"));\r\n");
      out.write("\t\t\t\t\t\t});\r\n");
      out.write("\t\t//上一张\r\n");
      out.write("\t\t$(\".photo-panel .photo-div .arrow-prv\")\r\n");
      out.write("\t\t\t\t.click(\r\n");
      out.write("\t\t\t\t\t\tfunction() {\r\n");
      out.write("\t\t\t\t\t\t\timg_index--;\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\tif (img_index < 0) {\r\n");
      out.write("\t\t\t\t\t\t\t\timg_index = $(\"#editForm .imgs .album img\").length - 1;\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\timg_src = $(\"#editForm .imgs .album img\").eq(\r\n");
      out.write("\t\t\t\t\t\t\t\t\timg_index).attr(\"src\");\r\n");
      out.write("\t\t\t\t\t\t\tphotoView($(\"#editForm .imgs .album img\"));\r\n");
      out.write("\t\t\t\t\t\t});\r\n");
      out.write("\t\t//如何调用？展示相册的图片\r\n");
      out.write("\t\t$(\".effect-2 .member-image img\").click(\r\n");
      out.write("\t\t\t\tfunction() {\r\n");
      out.write("\t\t\t\t\tvar albumId = $(this).attr(\"id\");\r\n");
      out.write("\t\t\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\t\ttype : \"POST\",\r\n");
      out.write("\t\t\t\t\t\turl : \"GetImgsByPage\", //根据相册id获取相册图片\r\n");
      out.write("\t\t\t\t\t\tdata : {\r\n");
      out.write("\t\t\t\t\t\t\t\"albumId\" : albumId\r\n");
      out.write("\t\t\t\t\t\t//需要获取照片的相册的id\r\n");
      out.write("\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\tsuccess : function(data) {\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\tvar imgs = eval(\"(\" + data + \")\");\r\n");
      out.write("\t\t\t\t\t\t\t//alert(\"相册照片数量：\"+imgs.length);\r\n");
      out.write("\t\t\t\t\t\t\tvar str = \"\";\r\n");
      out.write("\t\t\t\t\t\t\tvar p = document.getElementById(\"div_imgs\");\r\n");
      out.write("\t\t\t\t\t\t\tfor ( var i = 0; i < imgs.length; i++) {\r\n");
      out.write("\t\t\t\t\t\t\t\tvar item = imgs[i];\r\n");
      out.write("\t\t\t\t\t\t\t\t//alert(i);\r\n");
      out.write("\t\t\t\t\t\t\t\tstr += \"<div class=\\\"album\\\"><img src='\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t+ item.image_url.substring(1,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\titem.image_url.length)\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t+ \"'></div>\";\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\tp.innerHTML = str;\r\n");
      out.write("\t\t\t\t\t\t\tvar item = imgs[0];\r\n");
      out.write("\t\t\t\t\t\t\t$(\"#image_first\").attr(\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\"src\",\r\n");
      out.write("\t\t\t\t\t\t\t\t\titem.image_url.substring(1,\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\titem.image_url.length));\r\n");
      out.write("\t\t\t\t\t\t\t$(\".photo-mask\").show();\r\n");
      out.write("\t\t\t\t\t\t\t$(\".photo-panel\").show();\r\n");
      out.write("\t\t\t\t\t\t\timg_src = $(this).attr(\"src\");\r\n");
      out.write("\t\t\t\t\t\t\timg_index = $(this).index();\r\n");
      out.write("\t\t\t\t\t\t\tphotoView($(this));\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("\r\n");
      out.write("\t//自适应预览\r\n");
      out.write("\tfunction photoView(obj) {\r\n");
      out.write("\t\tif ($(obj).width() >= $(obj).height()) {\r\n");
      out.write("\t\t\t$(\".photo-panel .photo-div .photo-img .photo-view-h\").attr(\r\n");
      out.write("\t\t\t\t\t\"class\", \"photo-view-w\");\r\n");
      out.write("\t\t\t$(\".photo-panel .photo-div .photo-img .photo-view-w img\").attr(\r\n");
      out.write("\t\t\t\t\t\"src\", img_src);\r\n");
      out.write("\t\t} else {\r\n");
      out.write("\t\t\t$(\".photo-panel .photo-div .photo-img .photo-view-w\").attr(\r\n");
      out.write("\t\t\t\t\t\"class\", \"photo-view-h\");\r\n");
      out.write("\t\t\t$(\".photo-panel .photo-div .photo-img .photo-view-h img\").attr(\r\n");
      out.write("\t\t\t\t\t\"src\", img_src);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t//此处写调试日志\r\n");
      out.write("\t\tconsole.log(img_index);\r\n");
      out.write("\t} \r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- 分页 -->\r\n");
      out.write("\t<div class=\"tcdPageCode\">\r\n");
      out.write("\t\t");
      if (_jspx_meth_c_005fforEach_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("<!-- 底部 -->\r\n");
      out.write("<div class=\"Ifooter\" >\r\n");
      out.write("\t<p style=\"margin-left:35%;\">\r\n");
      out.write("\t  <span>copyright©2017 </span>\r\n");
      out.write("\t  <span style=\"margin-left: 20px;\">武汉科技大学党委宣传部</span>\r\n");
      out.write("\t</p>\r\n");
      out.write("\t<p style=\"margin-left:30%;\">\r\n");
      out.write("\t  <span>电话：027-68862542</span>\r\n");
      out.write("\t  <span style=\"margin-left: 10px;\">传真：027-68862461</span>\r\n");
      out.write("\t  <span style=\"margin-left: 10px;\">邮箱：xcb@wust.edu.cn</span>\r\n");
      out.write("\t</p>\r\n");
      out.write("\t <p style=\"margin-left:37%;\">\r\n");
      out.write("\t     <span>技术支持：武汉科技大学阿豆工作室 <a href=\"");
      if (_jspx_meth_c_005furl_005f3(_jspx_page_context))
        return;
      out.write("\">管理</a> </span>\r\n");
      out.write("\t     \r\n");
      out.write("\t </p>\r\n");
      out.write("</div>\r\n");
      out.write(" </body> \r\n");
      out.write(" </html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005furl_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f0 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    _jspx_th_c_005furl_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005furl_005f0.setParent(null);
    // /index.jsp(42,10) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005furl_005f0.setValue("/PraiseServlet");
    int _jspx_eval_c_005furl_005f0 = _jspx_th_c_005furl_005f0.doStartTag();
    if (_jspx_th_c_005furl_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f1 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    _jspx_th_c_005furl_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005furl_005f1.setParent(null);
    // /index.jsp(101,17) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005furl_005f1.setValue("/AlbumServlet");
    int _jspx_eval_c_005furl_005f1 = _jspx_th_c_005furl_005f1.doStartTag();
    if (_jspx_th_c_005furl_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f1);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f1);
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fforEach_005f0.setParent(null);
    // /index.jsp(185,4) name = items type = java.lang.Object reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setItems((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${albums}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
    // /index.jsp(185,4) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setVar("item");
    int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
    try {
      int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
      if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t\t<div class=\"album effect-2\">\r\n");
          out.write("\t\t\t\t\t\t<div class=\"member-image\">\r\n");
          out.write("\t\t\t\t\t\t\t<img id=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\" \r\n");
          out.write("\t\t\t\t\t\t\t\tsrc=\"");
          if (_jspx_meth_c_005furl_005f2(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
            return true;
          out.write("\">\r\n");
          out.write("\t\t\t\t\t\t</div>\r\n");
          out.write("\t\t\t\t\t\t<div class=\"member-info\">\r\n");
          out.write("\t\t\t\t\t\t\t<h3>\r\n");
          out.write("\t\t\t\t\t\t\t\t");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.albumName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("<img src=\"img/like.png\" id = \"praise");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\" onClick = \"praise(");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write(")\" \r\n");
          out.write("\t\t\t\t\t\t\t\t\tstyle=\"width: 22px;height: 22px;margin-left: 4px;\">\r\n");
          out.write("\t\t\t\t\t\t\t</h3>\r\n");
          out.write("\t\t\t\t\t\t\t<h5>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.userName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</h5>\r\n");
          out.write("\t\t\t\t\t\t\t");
          out.write("\r\n");
          out.write("\r\n");
          out.write("\t\t\t\t\t\t\t<div class=\"social-touch\">\r\n");
          out.write("\t\t\t\t\t\t\t\t<div class=\"fb-touch\"></div>\r\n");
          out.write("\t\t\t\t\t\t\t\t<div class=\"tweet-touch\"></div>\r\n");
          out.write("\t\t\t\t\t\t\t\t<div class=\"linkedin-touch\"></div>\r\n");
          out.write("\r\n");
          out.write("\t\t\t\t\t\t\t</div>\r\n");
          out.write("\t\t\t\t\t\t</div>\r\n");
          out.write("\t\t\t\t\t</div>\r\n");
          out.write("\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
    } finally {
      _jspx_th_c_005fforEach_005f0.doFinally();
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f2 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    _jspx_th_c_005furl_005f2.setPageContext(_jspx_page_context);
    _jspx_th_c_005furl_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
    // /index.jsp(189,13) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005furl_005f2.setValue((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.albumImage_url }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
    int _jspx_eval_c_005furl_005f2 = _jspx_th_c_005furl_005f2.doStartTag();
    if (_jspx_th_c_005furl_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f2);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f2);
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f1 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fstep_005fend_005fbegin.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    _jspx_th_c_005fforEach_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005fforEach_005f1.setParent(null);
    // /index.jsp(356,2) name = begin type = int reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f1.setBegin(((java.lang.Integer) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${currentPage-2<0? 1:currentPage-2}", int.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).intValue());
    // /index.jsp(356,2) name = end type = int reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f1.setEnd(((java.lang.Integer) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${currentPage+3}", int.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).intValue());
    // /index.jsp(356,2) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f1.setVar("item");
    // /index.jsp(356,2) name = step type = int reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f1.setStep(1);
    int[] _jspx_push_body_count_c_005fforEach_005f1 = new int[] { 0 };
    try {
      int _jspx_eval_c_005fforEach_005f1 = _jspx_th_c_005fforEach_005f1.doStartTag();
      if (_jspx_eval_c_005fforEach_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t");
          if (_jspx_meth_c_005fif_005f0(_jspx_th_c_005fforEach_005f1, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f1))
            return true;
          out.write("\r\n");
          out.write("\t\t");
          int evalDoAfterBody = _jspx_th_c_005fforEach_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fforEach_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_c_005fforEach_005f1[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_c_005fforEach_005f1.doCatch(_jspx_exception);
    } finally {
      _jspx_th_c_005fforEach_005f1.doFinally();
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fstep_005fend_005fbegin.reuse(_jspx_th_c_005fforEach_005f1);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f1, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f1)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f1);
    // /index.jsp(358,3) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item>0&&item<=totalPage}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
    if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("\t\t\t\t");
        if (_jspx_meth_c_005fif_005f1(_jspx_th_c_005fif_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f1))
          return true;
        out.write("\r\n");
        out.write("\t\t\t\t");
        if (_jspx_meth_c_005fif_005f2(_jspx_th_c_005fif_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f1))
          return true;
        out.write("\r\n");
        out.write("\t\t\t");
        int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f1)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f0);
    // /index.jsp(359,4) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item==currentPage}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
    if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("\t\t\t\t\t<a href=\"GetAlbumsByPage?currentPage=");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("\"><span\r\n");
        out.write("\t\t\t\t\t\tclass=\"current\">");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("</span>\r\n");
        out.write("\t\t\t\t\t</a>\r\n");
        out.write("\t\t\t\t");
        int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f1)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f2 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f2.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f0);
    // /index.jsp(364,4) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f2.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item!=currentPage}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_c_005fif_005f2 = _jspx_th_c_005fif_005f2.doStartTag();
    if (_jspx_eval_c_005fif_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("\t\t\t\t\t<a href=\"GetAlbumsByPage?currentPage=");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("\" class=\"tcdNumber\">");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("</a>\r\n");
        out.write("\t\t\t\t");
        int evalDoAfterBody = _jspx_th_c_005fif_005f2.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f2);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f2);
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f3 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    _jspx_th_c_005furl_005f3.setPageContext(_jspx_page_context);
    _jspx_th_c_005furl_005f3.setParent(null);
    // /index.jsp(383,38) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005furl_005f3.setValue("/Back/login.jsp");
    int _jspx_eval_c_005furl_005f3 = _jspx_th_c_005furl_005f3.doStartTag();
    if (_jspx_th_c_005furl_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f3);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f3);
    return false;
  }
}
