/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.33
 * Generated at: 2019-02-24 05:10:42 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class personalHomepage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/standard.jar", Long.valueOf(1491182579116L));
    _jspx_dependants.put("jar:file:/C:/Users/12611/OneDrive/code/eclipse_jee/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/sydsNew6/WEB-INF/lib/standard.jar!/META-INF/c.tld", Long.valueOf(1098682290000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.release();
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write(" <!-- 导航栏 -->\r\n");
      out.write("  <link rel=\"stylesheet\" type=\"text/css\" href=\"css/bootstrap.min.css\">\r\n");
      out.write("  <script type=\"text/javascript\" src=\"js/jquery-1.11.1.min.js\"></script>\r\n");
      out.write("  <script type=\"text/javascript\" src=\"js/bootstrap.min.js\"></script> \r\n");
      out.write("<!-- 登录注册弹出窗口 -->\r\n");
      out.write("  <link rel=\"stylesheet\" type=\"text/css\" href=\"css/tanchuchuangkou.css\"/>\r\n");
      out.write("  <script src=\"js/tanchuchuangkou.js\" type=\"text/javascript\" charset=\"utf-8\"></script>\r\n");
      out.write("  <script src=\"js/jQuery-placeholder.js\" type=\"text/javascript\" charset=\"utf-8\"></script>\r\n");
      out.write("  <link rel=\"stylesheet\" type=\"text/css\" href=\"css/index.css\">\r\n");
      out.write("  <link rel=\"stylesheet\" type=\"text/css\" href=\"css/style.css\" />\r\n");
      out.write("  <script src=\"js/style.js\"></script>\r\n");
      out.write("  \r\n");
      out.write("  <script src=\"js/jquery-3.1.1.min.js\"></script>\r\n");
      out.write("\t<meta name=\"viewport\" charset=\"UTF-8\" content=\"initial-scale=1.0,maximum-scale=1.0,minimum-scale=1.0,user-scalable=0,width=decice-width\"/>\r\n");
      out.write("\t<title>个人中心主页</title>\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"css/album.css\" />\r\n");
      out.write("\t<script src=\"js/style.js\"></script>\r\n");
      out.write("    <script src=\"layer/jquery.js?v=1.83.min\"></script>\r\n");
      out.write("    <script src=\"layer/layer.min.js\"></script>\r\n");
      out.write("    \r\n");
      out.write("    <script type=\"text/javascript\">\r\n");
      out.write("    $(document).ready(function() {\r\n");
      out.write("    //退出\r\n");
      out.write("  \t$('#quit').bind('click', function() {\r\n");
      out.write("  \t\t$.ajax({\r\n");
      out.write("\t\t\ttype : \"POST\",\r\n");
      out.write("\t\t\turl : 'UserServlet?method=quit',\r\n");
      out.write("\t\t\tdata : {},\r\n");
      out.write("\t\t\tsuccess : function(data) {\r\n");
      out.write("\t\t\t\tif (data == 'true') {\r\n");
      out.write("\t\t\t\t\talert(\"退出成功\");\r\n");
      out.write("\t\t\t\t\twindow.location = \"index0.jsp\"; \r\n");
      out.write("\t\t\t\t}else if(data == 'noLogin'){\r\n");
      out.write("\t\t\t\t\talert(\"请先登录\");\r\n");
      out.write("\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\talert(\"退出失败，请重新打开浏览器\");\r\n");
      out.write("\t\t\t\t\twindow.location.reload() ;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("  \t\t\r\n");
      out.write("  \t});\r\n");
      out.write("    }); \r\n");
      out.write("\r\n");
      out.write("        //增加相册\r\n");
      out.write("        $(function(){\r\n");
      out.write("        \t$(\".addAlbum\").unbind('click').click(function(){\r\n");
      out.write("        \t\t $('#editForm').show();\r\n");
      out.write("                 $('#fade').show();\r\n");
      out.write("                 $(\"#albumTitle\").val();\r\n");
      out.write("                 $(\"#albumDes\").val();\r\n");
      out.write("                 $(\"#span_delete\").hide();\r\n");
      out.write("                 $(\"#deleteAlbum\").hide();\r\n");
      out.write("                 $(\".btn\").val(\"添加\");\r\n");
      out.write("                \r\n");
      out.write("                 //添加相册\r\n");
      out.write("                 $(\"#addOrUpdate\").unbind('click').click(function(){\r\n");
      out.write("                \t if( $(\"#albumTitle\").val() == \"\"){\r\n");
      out.write("                \t\t alert(\"请输入作品集名称\");\r\n");
      out.write("                \t\t //return;\r\n");
      out.write("                \t }else  if( $(\"#albumTitle\").val().length > 9){\r\n");
      out.write("            \t\t\t alert(\"请注意输入的标题的长度\");\r\n");
      out.write("            \t\t }else{\r\n");
      out.write("            \t\t\t \r\n");
      out.write("                \t\t var url = \"");
      if (_jspx_meth_c_005furl_005f0(_jspx_page_context))
        return;
      out.write("?method=addAlbum\";\r\n");
      out.write("                         var albumName = $(\"#albumTitle\").val();\r\n");
      out.write("                    \t var description = $(\"#albumDes\").val();\r\n");
      out.write("                    \t if(description.length > 30){\r\n");
      out.write("                    \t\t alert(\"请注意输入的描述的长度\");\r\n");
      out.write("                    \t\t return;\r\n");
      out.write("                    \t }\r\n");
      out.write("                    \t if(description == \"描述不允许超过26个字符\" ){\r\n");
      out.write("                    \t\t description = \"\";\r\n");
      out.write("                    \t }\r\n");
      out.write("                    \t var params = {\"albumName\":albumName, \"description\":description};\r\n");
      out.write("                    \t $(this).load(url,params,function(data){\r\n");
      out.write("                    \t\t var jsonData = eval(\"(\"+data+\")\");\r\n");
      out.write("         \t\t\t\t\t$('#editForm').hide();\r\n");
      out.write("                            $('#fade').hide();\r\n");
      out.write("                            setTimeout(function(){  //使用  setTimeout（）方法设定定时2000毫秒\r\n");
      out.write("                         \t\twindow.location.reload();//页面刷新\r\n");
      out.write("                         \t\t},100);\r\n");
      out.write("         \t\t\t\t\t//windows.location =\"");
      if (_jspx_meth_c_005furl_005f1(_jspx_page_context))
        return;
      out.write("?method=queryAlbum\";\r\n");
      out.write("                    \t });\r\n");
      out.write("                    \t \r\n");
      out.write("                    \t \r\n");
      out.write("                         \r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("                \t \r\n");
      out.write("                 });\r\n");
      out.write("                 \r\n");
      out.write("                /*  $('.btn').click(function () {\r\n");
      out.write("                \t \r\n");
      out.write("                \t if( $(\"#albumTitle\").val() != \"\"){\r\n");
      out.write("                \t\t $('#main').append('<div class=\"album effect-2\"><div class=\"member-image\"><img src=\"images/album.jpg\" style=\"background: #fff;\"></div><div class=\"member-info\"><h3><a href=\"photoShow.html\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${album.albumName }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</a></h3><h5>albumName</h5><p><a href=\"photoShow.html\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${album.description }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</a></p><button type=\"button\" class=\"button grey\" onclick=\"dosomething()\">编辑</button></div><div class=\"social-touch\"><a class=\"fb-touch\" href=\"photoShow.html\"></a><a class=\"tweet-touch\" href=\"photoShow.html\"></a><a class=\"linkedin-touch\" href=\"photoShow.html\"></a></div></div>');\r\n");
      out.write("                         $('#editForm').hide();\r\n");
      out.write("                         $('#fade').hide();\r\n");
      out.write("                \t }else{\r\n");
      out.write("                \t\t  $('#editForm').show();\r\n");
      out.write("                          $('#fade').show();\r\n");
      out.write("                \t }\r\n");
      out.write("                 }); */\r\n");
      out.write("                \r\n");
      out.write("        \t});\r\n");
      out.write("        });\r\n");
      out.write("        \r\n");
      out.write("        //删除相册或修改相册\r\n");
      out.write("        function dosomething(index) {\r\n");
      out.write("        \tvar albumName =  $(\"[id='a_albumName\"+index+\"']\").text();\r\n");
      out.write("        \tvar description = $(\"[id='a_description\"+index+\"']\").text();\r\n");
      out.write("        \tvar userName = $(\"[id='h_userName']\").html();\r\n");
      out.write("        \t $(\"#albumTitle\").val(albumName);\r\n");
      out.write("             $(\"#albumDes\").val(description);\r\n");
      out.write("        \t $(\".btn\").val(\"保存设置\");\r\n");
      out.write("        \t $(\"#deleteAlbum\").show();\r\n");
      out.write("        \t if ($('.white_content').is(':hidden')) {\r\n");
      out.write("                 $('.white_content').show();\r\n");
      out.write("             }\r\n");
      out.write("             else {\r\n");
      out.write("                 $('.white_content').hide();\r\n");
      out.write("             }\r\n");
      out.write("        \t //删除相册\r\n");
      out.write("        \t $(\"#deleteAlbum\").click(function(){\r\n");
      out.write("        \t\t var url = \"");
      if (_jspx_meth_c_005furl_005f2(_jspx_page_context))
        return;
      out.write("?method=deleteAlbum\";\r\n");
      out.write("            \t var id = $(\"#album_id\"+index).val();\r\n");
      out.write("        \t\t var params = {\"id\":id};\r\n");
      out.write("            \t $(this).load(url,params,function(data){\r\n");
      out.write("            \t });\r\n");
      out.write("            \t $('#editForm').hide();\r\n");
      out.write("                 $('#fade').hide();\r\n");
      out.write("                 setTimeout(function(){  //使用  setTimeout（）方法设定定时2000毫秒\r\n");
      out.write("              \t\twindow.location.reload();//页面刷新\r\n");
      out.write("              \t\t},100);\r\n");
      out.write("        \t });\r\n");
      out.write("        \t\r\n");
      out.write("        \t //修改相册\r\n");
      out.write("        \t $(\"#addOrUpdate\").unbind('click').click(function(){\r\n");
      out.write("        \t\t if( $(\"#albumTitle\").val() == \"\"){\r\n");
      out.write("            \t\t alert(\"请输入作品集名称\");\r\n");
      out.write("            \t\t return;\r\n");
      out.write("            \t }\r\n");
      out.write("            \t var url = \"");
      if (_jspx_meth_c_005furl_005f3(_jspx_page_context))
        return;
      out.write("?method=alertAlbum\";\r\n");
      out.write("            \t var id = $(\"#album_id\"+index).val();\r\n");
      out.write("                 var albumNameNew = $(\"#albumTitle\").val();\r\n");
      out.write("            \t var description = $(\"#albumDes\").val();\r\n");
      out.write("            \t var params = {\"id\":id, \"albumName\":albumNameNew, \"description\":description};\r\n");
      out.write("            \t $(this).load(url,params,function(data){\r\n");
      out.write("            \t\t setTimeout(function(){  //使用  setTimeout（）方法设定定时2000毫秒\r\n");
      out.write("                   \t\twindow.location.reload();//页面刷新\r\n");
      out.write("                   \t\t},100);\r\n");
      out.write("            \t });\r\n");
      out.write("            \t $('#editForm').hide();\r\n");
      out.write("                 $('#fade').hide();\r\n");
      out.write("             });\r\n");
      out.write("        }\r\n");
      out.write("        \r\n");
      out.write("    </script>\r\n");
      out.write("</head>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <!--头部  -->\r\n");
      out.write("    <div class=\"header\">\r\n");
      out.write("   <img src=\"img/title.jpg\" style=\"width: 100%;height: auto;\">\r\n");
      out.write(" </div>\r\n");
      out.write("<nav class=\"nav navbar-inverse\" role=\"navgation\"> \r\n");
      out.write(" <div class=\"container-fluid\"> \r\n");
      out.write(" <div class=\"navbar-header\">\r\n");
      out.write("  <a class=\"navbar-brand\"> \r\n");
      out.write("   \r\n");
      out.write("  </a>\r\n");
      out.write("   <button class=\"navbar-toggle\" data-toggle=\"collapse\" data-target=\".navbar-collapse\"> \r\n");
      out.write("      <span class=\"icon-bar\"></span>\r\n");
      out.write("      <span class=\"icon-bar\"></span> \r\n");
      out.write("      <span class=\"icon-bar\"></span> \r\n");
      out.write("   </button>\r\n");
      out.write("    </div> \r\n");
      out.write("    <div class=\"collapse navbar-collapse\"> \r\n");
      out.write("    <ul class=\"navbar-nav nav\"> \r\n");
      out.write("    <li><a href=\"index0.jsp\">首页</a></li> \r\n");
      out.write("    <li><a href=\"introduction.jsp\">大赛简介</a></li> \r\n");
      out.write("    <li class=\"active\"><a href=\"");
      if (_jspx_meth_c_005furl_005f4(_jspx_page_context))
        return;
      out.write("?method=queryAlbum\">个人中心</a></li>\r\n");
      out.write("     </ul>\r\n");
      out.write("       <div class=\"navbar-form navbar-right\" style=\"margin-right: 30px;\"> \r\n");
      out.write("      <!-- <input type=\"text\" class=\"form-control\" name=\"\" id=\"searchStr\" placeholder=\"请输入搜索内容\"> \r\n");
      out.write("      <button class=\"btn btn-success\" style=\"margin-right: 30px;\">搜索</button> -->\r\n");
      out.write("       <!-- <a class=\"navbar-link\" javascript:void(0) id = \"register_id\" onClick=\"showBox1()\">注册</a> \r\n");
      out.write("       <a class=\"navbar-link\" javascript:void(0) id = \"login_id\" onClick=\"showBox()\">登录 </a>  -->\r\n");
      out.write("       <a class=\"navbar-link\" id = \"showUserName\" >");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.user.userName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</a>\r\n");
      out.write("       <a class=\"navbar-link\" style=\"cursor:pointer\" type = \"hidden\" id = \"quit\">退出</a>\r\n");
      out.write("       </div> \r\n");
      out.write("       </div>\r\n");
      out.write("        </div> \r\n");
      out.write("        </nav>\r\n");
      out.write("        <!--头部结束  -->\r\n");
      out.write("        \r\n");
      out.write("     <div id=\"container2\">\r\n");
      out.write("    \t<div class=\"banner\">\r\n");
      out.write("    \t   <div class=\"userpic\"><img src=\"img/username.png\"></div>\r\n");
      out.write("    \t   <div class=\"banner-context\">\r\n");
      out.write("    \t       <div class=\"banner-head\">\r\n");
      out.write("    \t   \t      <div class=\"banner-username\"><b id=\"t\" class=\"change\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.userName }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</b></div>\r\n");
      out.write("    \t   \t       \r\n");
      out.write("    \t   \t   </div>\r\n");
      out.write("    \t   \t   \r\n");
      out.write("    \t   \t   <div class=\"banner-userinfor\">\r\n");
      out.write("    \t   \t      <table>\r\n");
      out.write("                        <tr>\r\n");
      out.write("                            <td>学院：</td> \r\n");
      out.write("                            <td class=\"change\" style=\"display: inline-block;width: 200px;\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${unitName }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\r\n");
      out.write("                            <td>真实姓名：</td> \r\n");
      out.write("                            <td class=\"change\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.realName }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                        <tr>\r\n");
      out.write("                            <td>联系电话：</td> \r\n");
      out.write("                            <td class=\"change\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.phone }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                   </table>\r\n");
      out.write("    \t   \t   </div> \r\n");
      out.write("    \t   </div>\r\n");
      out.write("    \t   <div class=\"tabs\">\r\n");
      out.write("    \t   \t   <div class=\"tab\"><a href=\"");
      if (_jspx_meth_c_005furl_005f5(_jspx_page_context))
        return;
      out.write("?method=queryAlbum\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.countAlbum }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("作品集</a></div>\r\n");
      out.write("    \t   \t   <div class=\"tab\"><a href=\"\"><b>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.countImageByUser }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("照片</b></a></div>\r\n");
      out.write("    \t   \t   ");
      out.write("\r\n");
      out.write("    \t   \t   <div class=\"tab\" style=\"font-size:1em;color:red;border-right:0;font-weight:bold;\">上传照片流程：1）请先建立一个相册  2）点击新相册，进入相册里面进行照片上传</div>\r\n");
      out.write("    \t   </div>\r\n");
      out.write("    \t</div>\r\n");
      out.write("    \t\r\n");
      out.write("    \t<!-- 那个弹出的窗口 -->\r\n");
      out.write("    \t<div id=\"fade\" class=\"black_overlay\"></div>\r\n");
      out.write("            <div id=\"editForm\" class=\"white_content\">\r\n");
      out.write("            <div style=\"text-align: right; cursor: default; height: 40px;margin-right: 30px\">\r\n");
      out.write("            <span style=\"font-size: 16px;\" onclick=\"hideDiv('editForm','fade')\">关闭</span>\r\n");
      out.write("            </div>\r\n");
      out.write("             <form id=\"edit\"  method=\"post\" target=\"frame\">\r\n");
      out.write("                <div style=\"font-size: 1.5em;font-weight: bold;color:#202020;margin-bottom: 30px\"><span>新增作品集</span><span style=\"color:#587265;\"><b></b></span></div><br/>\r\n");
      out.write("                <div><span class=\"spanWidth\">标题</span><input type=\"text\" id = \"albumTitle\" name = \"albumName\" style=\"width: 400px;height: 30px;\" placeholder=\"标题不允许超过9个字符\"></div><br/>\r\n");
      out.write("                <div><span class=\"spanWidth\">描述</span><input type=\"text\" id = \"albumDes\" name = \"description\" style=\"width: 400px;height: 80px\" placeholder=\"描述不允许超过26个字符\"></div><br/>\r\n");
      out.write("                <div><span class=\"spanWidth\" id = \"span_delete\">删除</span><input type=\"button\" class=\"button\" value=\"删除作品集\" id=\"deleteAlbum\" style=\"width: 200px;height: 50px;border: 1px solid #aeafae;\" onclick=\"\"></div><br/>\r\n");
      out.write("                <div><input type=\"submit\" id = \"addOrUpdate\" class=\"btn\" value=\"保存设置\" style=\"width: 250px;height: 60px;background: #587265;font-size: 1em;color: #fff;\"></div>\r\n");
      out.write("            </form>\r\n");
      out.write("       </div>\r\n");
      out.write("\r\n");
      out.write("        <div id=\"main\">\r\n");
      out.write("           <div class=\"album\">\r\n");
      out.write("                <div class=\"inner\">\r\n");
      out.write("                    <a  href=\"javascript:void(0)\" style=\"display: inline-block;\" >\r\n");
      out.write("                    <img class = \"addAlbum\" src=\"images/add.png\" >\r\n");
      out.write("                    <span style=\"display: inline-block;font-size: 0.8em;color: #666666;margin-left:28%;\">新增作品集</span>\r\n");
      out.write("                    </a> \r\n");
      out.write("                </div>\r\n");
      out.write("           </div>\r\n");
      out.write("           ");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("    \t</div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!--底部  -->\r\n");
      out.write("\t<div class=\"Ifooter\">\r\n");
      out.write("    <p style=\"margin-left:35%;\">\r\n");
      out.write("      <span>copyright©2017 </span>\r\n");
      out.write("      <span style=\"margin-left: 20px;\">武汉科技大学党委宣传部</span>\r\n");
      out.write("    </p>\r\n");
      out.write("    <p style=\"margin-left:30%;\">\r\n");
      out.write("      <span>电话：027-68862542</span>\r\n");
      out.write("      <span style=\"margin-left: 10px;\">传真：027-68862461</span>\r\n");
      out.write("      <span style=\"margin-left: 10px;\">邮箱：xcb@wust.edu.cn</span>\r\n");
      out.write("    </p>\r\n");
      out.write("     <p style=\"margin-left:37%;\"><span>技术支持：武汉科技大学阿豆工作室</span></p>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!--登录  注册-->\r\n");
      out.write("<!-- 登录注册弹出窗口 -->\r\n");
      out.write("<!-- 注册窗口 -->\r\n");
      out.write("<div class=\"event\" id=\"register_box\" style=\"display: none;\">\r\n");
      out.write("    <div class=\"register\">\r\n");
      out.write("      <div class=\"title\">\r\n");
      out.write("        <img class=\"t_txt\" src=\"images/logo.png\" style=\"width: 200px;height:45px; \">\r\n");
      out.write("        <span class=\"del\" onClick=\"deleteRegister()\">X</span>\r\n");
      out.write("      </div>\r\n");
      out.write("    <form  id=\"\" action=\"\" method=\"post\" name=\"form1\">\r\n");
      out.write("               <input  placeholder=\"请输入用户名\" name=\"uid\" type=\"text\" id=\"uid\">\r\n");
      out.write("               <input  placeholder=\"请输入密码\" name=\"psw1\" type=\"password\" id=\"psw1\">\r\n");
      out.write("               <input  placeholder=\"请确认密码\" name=\"psw2\" type=\"password\" id=\"psw2\" >\r\n");
      out.write("               <select name=\"department\" onChange=\"getDeparment()\" id=\"\">\r\n");
      out.write("                  <option value=\"0\">请选择参赛组织</option>\r\n");
      out.write("                  <option value=\"职能部门\">职能部门</option>\r\n");
      out.write("                  <option value=\"学院\">学院</option>\r\n");
      out.write("               </select>\r\n");
      out.write("               <select name=\"academy\" id=\"\">\r\n");
      out.write("               <option value=\"0\">请选择参赛单位</option>\r\n");
      out.write("               </select>\r\n");
      out.write("             \r\n");
      out.write("               <input type=\"text\" name=\"username\" id=\"username\" value=\"\" placeholder=\"姓名\"/>\r\n");
      out.write("               <input type=\"text\" name=\"phone\" id=\"phone\"  placeholder=\"联系方式\" />\r\n");
      out.write("               <input type=\"submit\" name=\"tregister\" id=\"tregister\" value=\"注册\" class=\"btnR\" style=\"color: #ffffff;\" />\r\n");
      out.write("             <div><a class=\"RL\" javascript:void(0) onClick=\"showBox2()\">已有账号？去登录</a>\r\n");
      out.write("             </div>\r\n");
      out.write("            </div>\r\n");
      out.write("     </form> \r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("  <div class=\"bg_color\" onClick=\"deleteRegister()\" id=\"bg_filter\" style=\"display: none;\"></div>\r\n");
      out.write("<!-- 登录弹出窗口 -->\r\n");
      out.write("<div class=\"event\" id=\"login_box\" style=\"display: none;\">\r\n");
      out.write("    <div class=\"login\">\r\n");
      out.write("      <div class=\"title\">\r\n");
      out.write("        <img class=\"t_txt\" src=\"images/logo.png\" style=\"width: 200px;height:45px; \">\r\n");
      out.write("        <span class=\"del\" onClick=\"deleteLogin()\">X</span>\r\n");
      out.write("      </div>\r\n");
      out.write("      <form action=\"\" method=\"post\">\r\n");
      out.write("        <input type=\"text\" name=\"\" id=\"\" value=\"\" placeholder=\"请输入用户名\"/>\r\n");
      out.write("        <input type=\"password\" name=\"\" id=\"\" value=\"\" placeholder=\"请输入密码\"/>\r\n");
      out.write("        <input type=\"button\" name=\"\" id=\"\" value=\"登录\" class=\"btnR\" style=\"color: #ffffff;\" />    \r\n");
      out.write("        <div><a class=\"RL\"  javascript:void(0) onClick=\"showBox3()\">还没有账号？去注册</a></div>\r\n");
      out.write("      </form> \r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("  <div class=\"bg_color\" onClick=\"deleteLogin()\" id=\"bg_filter\" style=\"display: none;\">\r\n");
      out.write("  </div>\t\r\n");
      out.write("  \r\n");
      out.write("<!--登录  注册结束-->\r\n");
      out.write("<!-- 弹出提示框 -->\r\n");
      out.write("<div id=\"editForm1\" class=\"white_tip\">\r\n");
      out.write("            <div style=\"text-align: right; cursor: default; height: 40px;margin-right: 30px\">\r\n");
      out.write("            <span style=\"font-size: 16px;\" onclick=\"hideDiv('editForm','fade')\">关闭</span>\r\n");
      out.write("            </div>\r\n");
      out.write("             wenzi\r\n");
      out.write("       </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005furl_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f0 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    _jspx_th_c_005furl_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005furl_005f0.setParent(null);
    // /personalHomepage.jsp(70,30) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005furl_005f0.setValue("/AlbumServlet");
    int _jspx_eval_c_005furl_005f0 = _jspx_th_c_005furl_005f0.doStartTag();
    if (_jspx_th_c_005furl_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f1 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    _jspx_th_c_005furl_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005furl_005f1.setParent(null);
    // /personalHomepage.jsp(88,35) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005furl_005f1.setValue("/AlbumServlet");
    int _jspx_eval_c_005furl_005f1 = _jspx_th_c_005furl_005f1.doStartTag();
    if (_jspx_th_c_005furl_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f1);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f1);
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f2 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    _jspx_th_c_005furl_005f2.setPageContext(_jspx_page_context);
    _jspx_th_c_005furl_005f2.setParent(null);
    // /personalHomepage.jsp(129,22) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005furl_005f2.setValue("/AlbumServlet");
    int _jspx_eval_c_005furl_005f2 = _jspx_th_c_005furl_005f2.doStartTag();
    if (_jspx_th_c_005furl_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f2);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f2);
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f3 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    _jspx_th_c_005furl_005f3.setPageContext(_jspx_page_context);
    _jspx_th_c_005furl_005f3.setParent(null);
    // /personalHomepage.jsp(147,25) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005furl_005f3.setValue("/AlbumServlet");
    int _jspx_eval_c_005furl_005f3 = _jspx_th_c_005furl_005f3.doStartTag();
    if (_jspx_th_c_005furl_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f3);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f3);
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f4(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f4 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    _jspx_th_c_005furl_005f4.setPageContext(_jspx_page_context);
    _jspx_th_c_005furl_005f4.setParent(null);
    // /personalHomepage.jsp(186,32) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005furl_005f4.setValue("/AlbumServlet");
    int _jspx_eval_c_005furl_005f4 = _jspx_th_c_005furl_005f4.doStartTag();
    if (_jspx_th_c_005furl_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f4);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f4);
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f5(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f5 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    _jspx_th_c_005furl_005f5.setPageContext(_jspx_page_context);
    _jspx_th_c_005furl_005f5.setParent(null);
    // /personalHomepage.jsp(226,38) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005furl_005f5.setValue("/AlbumServlet");
    int _jspx_eval_c_005furl_005f5 = _jspx_th_c_005furl_005f5.doStartTag();
    if (_jspx_th_c_005furl_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f5);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f5);
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fforEach_005f0.setParent(null);
    // /personalHomepage.jsp(257,11) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setVar("item");
    // /personalHomepage.jsp(257,11) name = items type = java.lang.Object reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setItems((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${albumList }", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
    // /personalHomepage.jsp(257,11) name = varStatus type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setVarStatus("status");
    int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
    try {
      int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
      if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("            <div id = \"div_album\" class=\"album effect-2\">\r\n");
          out.write("              <div class=\"member-image\">\r\n");
          out.write("                ");
          if (_jspx_meth_c_005fif_005f0(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
            return true;
          out.write("\r\n");
          out.write("                ");
          if (_jspx_meth_c_005fif_005f1(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
            return true;
          out.write("\r\n");
          out.write("              </div>\r\n");
          out.write("              <div class=\"member-info\">\r\n");
          out.write("                   <h3><a href=\"ImageServlet?method=queryImagesBA&id=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.id }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("&albumImage_url=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.albumImage_url}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("&albumName=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.albumName }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\" id = \"a_albumName");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${status.count}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\" class = \"albumInfo\" >");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.albumName }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</a></h3>\r\n");
          out.write("                   <h5 id = \"h_userName\" >");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.userName }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</h5>\r\n");
          out.write("                   <input type = \"hidden\" id = \"album_id");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${status.count}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\" value = \"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.id }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\">\r\n");
          out.write("                   <p><a href=\"ImageServlet?method=queryImagesBA&id=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.id }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("&albumImage_url=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.albumImage_url}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("&albumName=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.albumName }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\" id = \"a_description");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${status.count}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\"  class = \"albumInfo\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.description }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</a></p>\r\n");
          out.write("                   <button type=\"button\" class=\"button grey\" onclick=\"dosomething(");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${status.count}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write(")\">编辑</button>\r\n");
          out.write("                   </div><div class=\"social-touch\"><a class=\"fb-touch\" href=\"ImageServlet?method=queryImagesBA&id=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.id }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("&albumImage_url=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.albumImage_url}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("&albumName=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.albumName }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\"></a>\r\n");
          out.write("                   <a class=\"tweet-touch\" href=\"ImageServlet?method=queryImagesBA&id=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.id }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("&albumImage_url=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.albumImage_url}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("&albumName=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.albumName }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\"></a>\r\n");
          out.write("                   <a class=\"linkedin-touch\" href=\"ImageServlet?method=queryImagesBA&id=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.id }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("&albumImage_url=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.albumImage_url}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("&albumName=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.albumName }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\"></a>\r\n");
          out.write("               </div>\r\n");
          out.write("            </div>\r\n");
          out.write("            ");
          int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
    } finally {
      _jspx_th_c_005fforEach_005f0.doFinally();
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
    // /personalHomepage.jsp(260,16) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.albumImage_url != '' }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
    if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("                       <a href=\"ImageServlet?method=queryImagesBA&id=");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.id }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("&albumImage_url=");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.albumImage_url}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("&albumName=");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.albumName }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("\">\r\n");
        out.write("\t                   <img src=\"");
        if (_jspx_meth_c_005furl_005f6(_jspx_th_c_005fif_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
          return true;
        out.write("\"  style=\"background: #fff;\">\r\n");
        out.write("\t                   </a>\r\n");
        out.write("                ");
        int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f6(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f6 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    _jspx_th_c_005furl_005f6.setPageContext(_jspx_page_context);
    _jspx_th_c_005furl_005f6.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f0);
    // /personalHomepage.jsp(262,30) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005furl_005f6.setValue((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.albumImage_url }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
    int _jspx_eval_c_005furl_005f6 = _jspx_th_c_005furl_005f6.doStartTag();
    if (_jspx_th_c_005furl_005f6.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f6);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f6);
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
    // /personalHomepage.jsp(265,16) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.albumImage_url == '' }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
    if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("                       <a href=\"ImageServlet?method=queryImagesBA&id=");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.id }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("&albumImage_url=");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.albumImage_url}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("&albumName=");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${item.albumName }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("\">\r\n");
        out.write("\t                   <img src=\"img/username.png\"  style=\"background: #fff;\">\r\n");
        out.write("\t                   </a>\r\n");
        out.write("                ");
        int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
    return false;
  }
}
