/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.33
 * Generated at: 2019-02-24 05:14:05 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class photoShow_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/standard.jar", Long.valueOf(1491182579116L));
    _jspx_dependants.put("jar:file:/C:/Users/12611/OneDrive/code/eclipse_jee/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/sydsNew6/WEB-INF/lib/standard.jar!/META-INF/c.tld", Long.valueOf(1098682290000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("\t<meta name=\"viewport\" charset=\"UTF-8\" content=\"initial-scale=1.0,maximum-scale=1.0,minimum-scale=1.0,user-scalable=0,width=decice-width\"/>\r\n");
      out.write("\t<title>照片展示</title>\r\n");
      out.write("\t<link rel=\"stylesheet\" type=\"text/css\" href=\"css/style.css\" />\r\n");
      out.write("\t<script src=\"js/style.js\"></script>\r\n");
      out.write("\t<script src=\"js/jquery-3.1.1.min.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\">  \r\n");
      out.write("    $(document).ready(function() {\r\n");
      out.write("        //退出\r\n");
      out.write("      \t$('#quit').bind('click', function() {\r\n");
      out.write("      \t\t$.ajax({\r\n");
      out.write("    \t\t\ttype : \"POST\",\r\n");
      out.write("    \t\t\turl : 'UserServlet?method=quit',\r\n");
      out.write("    \t\t\tdata : {},\r\n");
      out.write("    \t\t\tsuccess : function(data) {\r\n");
      out.write("    \t\t\t\tif (data == 'true') {\r\n");
      out.write("    \t\t\t\t\talert(\"退出成功\");\r\n");
      out.write("    \t\t\t\t\twindow.location = \"index0.jsp\"; \r\n");
      out.write("    \t\t\t\t}else if(data == 'noLogin'){\r\n");
      out.write("    \t\t\t\t\talert(\"请先登录\");\r\n");
      out.write("    \t\t\t\t}else{\r\n");
      out.write("    \t\t\t\t\talert(\"退出失败，请重新打开浏览器\");\r\n");
      out.write("    \t\t\t\t\twindow.location.reload() ;\r\n");
      out.write("    \t\t\t\t}\r\n");
      out.write("    \t\t\t}\r\n");
      out.write("    \t\t});\r\n");
      out.write("      \t\t\r\n");
      out.write("      \t});\r\n");
      out.write("        }); \r\n");
      out.write("    \r\n");
      out.write("      //修改或删除图片\r\n");
      out.write("        function alertOrDelete(index){\r\n");
      out.write("          \t var album_id = $(\"#album_id\").val();\r\n");
      out.write("          \t var url = \"");
      if (_jspx_meth_c_005furl_005f0(_jspx_page_context))
        return;
      out.write("?method=deleteImage\";\r\n");
      out.write("     \t\t var image_id = $(\"#image_id\"+index).val();\r\n");
      out.write("     \t\t var image_url = $(\"#id_image_url\"+index).val();\r\n");
      out.write("     \t\t var params = {\"image_id\":image_id,\"image_url\":image_url};\r\n");
      out.write("         \t $(this).load(url,params,function(data){\r\n");
      out.write("         \t\t var jsonData = eval(\"(\"+data+\")\");\r\n");
      out.write("         \t });\r\n");
      out.write("         \tsetTimeout(function(){  //使用  setTimeout（）方法设定定时2000毫秒\r\n");
      out.write("         \t\twindow.location.reload();//页面刷新\r\n");
      out.write("         \t\t},100);\r\n");
      out.write("        };\r\n");
      out.write("        \r\n");
      out.write("    </script>\r\n");
      out.write("\r\n");
      out.write("    <!-- 导航栏 -->\r\n");
      out.write("  <link rel=\"stylesheet\" type=\"text/css\" href=\"css/bootstrap.min.css\">\r\n");
      out.write("  <script type=\"text/javascript\" src=\"js/jquery-1.11.1.min.js\"></script>\r\n");
      out.write("  <script type=\"text/javascript\" src=\"js/bootstrap.min.js\"></script> \r\n");
      out.write("  <!-- 登录注册弹出窗口 -->\r\n");
      out.write("  <link rel=\"stylesheet\" type=\"text/css\" href=\"css/tanchuchuangkou.css\"/>\r\n");
      out.write("  <script src=\"js/tanchuchuangkou.js\" type=\"text/javascript\" charset=\"utf-8\"></script>\r\n");
      out.write("  <script src=\"js/jQuery-placeholder.js\" type=\"text/javascript\" charset=\"utf-8\"></script>\r\n");
      out.write("  <link rel=\"stylesheet\" type=\"text/css\" href=\"css/index.css\"/>\r\n");
      out.write("  <style type=\"text/css\">\r\n");
      out.write("  .imgs .album img{\r\n");
      out.write("  width: 90%;\r\n");
      out.write("  height: 80%;\r\n");
      out.write("  margin: 5% 5% 0 5%;\r\n");
      out.write("  position: relative;\r\n");
      out.write("  text-decoration: none;\r\n");
      out.write("  display: inline-block;\r\n");
      out.write("  background-position:center center;\r\n");
      out.write("  background-repeat: no-repeat;\r\n");
      out.write("  \r\n");
      out.write("  background-size:cover;\r\n");
      out.write("  -moz-background-size:cover;\r\n");
      out.write("  -webkit-background-size:cover;\r\n");
      out.write("}\r\n");
      out.write("  </style>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"header\">\r\n");
      out.write("   <img src=\"img/title.jpg\" style=\"width: 100%;height: auto;\">\r\n");
      out.write(" </div>\r\n");
      out.write("<!--  导航栏 -->\r\n");
      out.write("<nav class=\"nav navbar-inverse\" role=\"navgation\"> \r\n");
      out.write(" <div class=\"container-fluid\"> \r\n");
      out.write(" <div class=\"navbar-header\">\r\n");
      out.write("  <a class=\"navbar-brand\"> \r\n");
      out.write("  </a>\r\n");
      out.write("   <button class=\"navbar-toggle\" data-toggle=\"collapse\" data-target=\".navbar-collapse\"> \r\n");
      out.write("      <span class=\"icon-bar\"></span>\r\n");
      out.write("      <span class=\"icon-bar\"></span> \r\n");
      out.write("      <span class=\"icon-bar\"></span> \r\n");
      out.write("   </button>\r\n");
      out.write("    </div> \r\n");
      out.write("    <div class=\"collapse navbar-collapse\"> \r\n");
      out.write("    <ul class=\"navbar-nav nav\"> \r\n");
      out.write("    <li><a href=\"index0.jsp\">首页</a></li> \r\n");
      out.write("    <li><a href=\"introduction.jsp\">大赛简介</a></li> \r\n");
      out.write("    <li class=\"active\"><a href=\"");
      if (_jspx_meth_c_005furl_005f1(_jspx_page_context))
        return;
      out.write("?method=queryAlbum\">个人中心</a></li>\r\n");
      out.write("     </ul>\r\n");
      out.write("      <div class=\"navbar-form navbar-right\" style=\"margin-right: 30px;\"> \r\n");
      out.write("     <!--  <input type=\"text\" class=\"form-control\" name=\"\" placeholder=\"请输入搜索内容\"> \r\n");
      out.write("      <button class=\"btn btn-success\" style=\"margin-right: 30px;\">搜索</button> -->\r\n");
      out.write("       <!-- <a class=\"navbar-link\" javascript:void(0) onClick=\"showBox1()\">注册</a> \r\n");
      out.write("       <a class=\"navbar-link\" javascript:void(0) onClick=\"showBox()\">登录 </a>  -->      \r\n");
      out.write("        <a class=\"navbar-link\" id = \"showUserName\" >");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.user.userName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</a>\r\n");
      out.write("       <a class=\"navbar-link\" type = \"hidden\" style=\"cursor:pointer\" id = \"quit\">退出</a>\r\n");
      out.write("       </div> \r\n");
      out.write("     </div>\r\n");
      out.write("    </div> \r\n");
      out.write("</nav>\r\n");
      out.write("<!--头部结束  -->\r\n");
      out.write("\r\n");
      out.write("    <div id=\"container2\">\r\n");
      out.write("    \t<div class=\"banner\">\r\n");
      out.write("    \t   <div class=\"userpic\"><img src=\"img/username.png\"></div>\r\n");
      out.write("    \t   <div class=\"banner-context\">\r\n");
      out.write("    \t       <div class=\"banner-head\">\r\n");
      out.write("    \t   \t      <div class=\"banner-username\"><b id=\"t\" class=\"change\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.userName }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</b></div>\r\n");
      out.write("    \t   \t       \r\n");
      out.write("    \t   \t    </div>\r\n");
      out.write("    \t   \t   <div class=\"banner-userinfor\">\r\n");
      out.write("    \t   \t      <table>\r\n");
      out.write("                        <tr>\r\n");
      out.write("                            <td>学院：</td> \r\n");
      out.write("                            <td class=\"change\" style=\"display: inline-block;width: 200px;\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${unitName }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\r\n");
      out.write("                            <td>真实姓名：</td> \r\n");
      out.write("                            <td class=\"change\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.realName }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                        <tr>\r\n");
      out.write("                            <td>联系电话：</td> \r\n");
      out.write("                            <td class=\"change\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.phone }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                   </table>\r\n");
      out.write("    \t   \t   </div> \r\n");
      out.write("    \t   </div>\r\n");
      out.write("    \t   <div class=\"tabs\">\r\n");
      out.write("    \t   \t   <div class=\"tab\"><a href=\"");
      if (_jspx_meth_c_005furl_005f2(_jspx_page_context))
        return;
      out.write("?method=queryAlbum\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.countAlbum }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("作品集</a></div>\r\n");
      out.write("    \t   \t   <div class=\"tab\"><a href=\"\"><b>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.countImageByAlbum }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("照片</b></a></div>\r\n");
      out.write("    \t   \t   <div class=\"tab\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.countPraise }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("赞</div>\r\n");
      out.write("    \t   </div>\r\n");
      out.write("    \t</div>\r\n");
      out.write("\r\n");
      out.write("        <!-- 点击作品集封面上的“编辑按钮”，弹出修改窗口 -->\r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!--照片的编写-->\r\n");
      out.write("\r\n");
      out.write("        <div id=\"main\">\r\n");
      out.write("           <div class=\"album\">\r\n");
      out.write("                <div class=\"inner\">\r\n");
      out.write("                    <a href=\"uploadPic.jsp\" style=\"display: inline-block;\" >\r\n");
      out.write("                    <img src=\"img/add.png\">\r\n");
      out.write("                    <span style=\"display: inline-block;font-size: 0.8em;color: #666666;margin-left:15%;width: 100px;height: auto;text-align: center;\">新增照片</span>\r\n");
      out.write("                    </a>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("           \r\n");
      out.write("                \r\n");
      out.write("            <div class=\"imgs\">\r\n");
      out.write("                 ");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("    \r\n");
      out.write("                    <!-- <div class=\"album\">\r\n");
      out.write("                    <img src=\"img/photo4.jpg\">\r\n");
      out.write("                    <button type=\"button\" class=\"button gray\" onclick=\"popDiv('editForm','fade')\">编辑</button></div>  -->\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("  \r\n");
      out.write("                \r\n");
      out.write("        <div class=\"photo-mask\"></div>\r\n");
      out.write("        <div class=\"photo-panel\">\r\n");
      out.write("            <div class=\"photo-div\">\r\n");
      out.write("               <div class=\"photo-left\">\r\n");
      out.write("                    <div class=\"arrow-prv\"></div>\r\n");
      out.write("               </div>\r\n");
      out.write("               <div class=\"photo-img\">\r\n");
      out.write("                    <div class=\"photo-bar\">\r\n");
      out.write("                        <div class=\"photo-close\"></div>\r\n");
      out.write("                    </div>\r\n");
      out.write("            \r\n");
      out.write("                    <div class=\"photo-view-h\">\r\n");
      out.write("                        <img src=\"http://b.zol-img.com.cn/sjbizhi/images/9/800x1280/1471524533521.jpg\" />\r\n");
      out.write("                    </div>\r\n");
      out.write("               </div>\r\n");
      out.write("               \r\n");
      out.write("               <div class=\"photo-right\">\r\n");
      out.write("                    <div class=\"arrow-next\"></div>\r\n");
      out.write("               </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("           \r\n");
      out.write("           \r\n");
      out.write("<script src=\"js/jquery.min.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("    var img_index = 0;\r\n");
      out.write("    var img_src = \"\";\r\n");
      out.write("\r\n");
      out.write("    $(function() {\r\n");
      out.write("        //计算居中位置\r\n");
      out.write("        var mg_top = ((parseInt($(window).height()) - parseInt($(\".photo-div\").height())) / 2);\r\n");
      out.write("\r\n");
      out.write("        $(\".photo-div\").css({\r\n");
      out.write("            \"margin-top\": \"\" + mg_top + \"px\"\r\n");
      out.write("        });\r\n");
      out.write("        //关闭\r\n");
      out.write("        $(\".photo-close\").click(function() {\r\n");
      out.write("            $(\".photo-mask\").hide();\r\n");
      out.write("            $(\".photo-panel\").hide();\r\n");
      out.write("        });\r\n");
      out.write("        //下一张\r\n");
      out.write("        $(\".photo-panel .photo-div .arrow-next\").click(function() {\r\n");
      out.write("            img_index++;\r\n");
      out.write("            if(img_index >= $(\".imgs .album img\").length) {\r\n");
      out.write("                img_index = 0;\r\n");
      out.write("            }\r\n");
      out.write("            img_src = $(\".imgs .album img\").eq(img_index).attr(\"src\");\r\n");
      out.write("            photoView($(\".imgs .album img\"));\r\n");
      out.write("        });\r\n");
      out.write("        //上一张\r\n");
      out.write("        $(\".photo-panel .photo-div .arrow-prv\").click(function() {\r\n");
      out.write("            img_index--;\r\n");
      out.write("            if(img_index < 0) {\r\n");
      out.write("                img_index = $(\".imgs .album img\").length - 1;\r\n");
      out.write("            }\r\n");
      out.write("            img_src = $(\".imgs .album img\").eq(img_index).attr(\"src\");\r\n");
      out.write("            photoView($(\".imgs .album img\"));\r\n");
      out.write("        });\r\n");
      out.write("        //如何调用？\r\n");
      out.write("        $(\".imgs .album img\").click(function() {\r\n");
      out.write("\r\n");
      out.write("            $(\".photo-mask\").show();\r\n");
      out.write("            $(\".photo-panel\").show();\r\n");
      out.write("            img_src = $(this).attr(\"src\");\r\n");
      out.write("            img_index = $(this).index();\r\n");
      out.write("            photoView($(this));\r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("    });\r\n");
      out.write("    //自适应预览\r\n");
      out.write("    function photoView(obj) {\r\n");
      out.write("        if($(obj).width() >= $(obj).height()) {\r\n");
      out.write("            $(\".photo-panel .photo-div .photo-img .photo-view-h\").attr(\"class\", \"photo-view-w\");\r\n");
      out.write("            $(\".photo-panel .photo-div .photo-img .photo-view-w img\").attr(\"src\", img_src);\r\n");
      out.write("        } else {\r\n");
      out.write("            $(\".photo-panel .photo-div .photo-img .photo-view-w\").attr(\"class\", \"photo-view-h\");\r\n");
      out.write("            $(\".photo-panel .photo-div .photo-img .photo-view-h img\").attr(\"src\", img_src);\r\n");
      out.write("        }\r\n");
      out.write("        //此处写调试日志\r\n");
      out.write("        console.log(img_index);\r\n");
      out.write("    }\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("    <!-- 底部 -->\r\n");
      out.write("<div class=\"Ifooter\" style=\"margin-top: 20px;\">\r\n");
      out.write("    <p style=\"margin-left:35%;\">\r\n");
      out.write("      <span>copyright©2017 </span>\r\n");
      out.write("      <span style=\"margin-left: 20px;\">武汉科技大学党委宣传部</span>\r\n");
      out.write("    </p>\r\n");
      out.write("    <p style=\"margin-left:30%;\">\r\n");
      out.write("      <span>电话：027-68862542</span>\r\n");
      out.write("      <span style=\"margin-left: 10px;\">传真：027-68862461</span>\r\n");
      out.write("      <span style=\"margin-left: 10px;\">邮箱：xcb@wust.edu.cn</span>\r\n");
      out.write("    </p>\r\n");
      out.write("     <p style=\"margin-left:37%;\"><span>技术支持：武汉科技大学阿豆工作室</span></p>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- 登录注册弹出窗口 -->\r\n");
      out.write("<!-- 注册窗口 -->\r\n");
      out.write("<div class=\"event\" id=\"register_box\" style=\"display: none;\">\r\n");
      out.write("    <div class=\"register\">\r\n");
      out.write("      <div class=\"title\">\r\n");
      out.write("        <img class=\"t_txt\" src=\"images/logo.png\" style=\"width: 200px;height:45px; \">\r\n");
      out.write("        <span class=\"del\" onClick=\"deleteRegister()\">X</span>\r\n");
      out.write("      </div>\r\n");
      out.write("    <form  id=\"\" action=\"\" method=\"post\" name=\"form1\">\r\n");
      out.write("               <input  placeholder=\"请输入用户名\" name=\"uid\" type=\"text\" id=\"uid\">\r\n");
      out.write("               <input  placeholder=\"请输入密码\" name=\"psw1\" type=\"password\" id=\"psw1\">\r\n");
      out.write("               <input  placeholder=\"请确认密码\" name=\"psw2\" type=\"password\" id=\"psw2\" >\r\n");
      out.write("               <select name=\"department\" onChange=\"getDeparment()\" id=\"\">\r\n");
      out.write("                  <option value=\"0\">请选择参赛组织</option>\r\n");
      out.write("                  <option value=\"职能部门\">职能部门</option>\r\n");
      out.write("                  <option value=\"学院\">学院</option>\r\n");
      out.write("               </select>\r\n");
      out.write("               <select name=\"academy\" id=\"\">\r\n");
      out.write("               <option value=\"0\">请选择参赛单位</option>\r\n");
      out.write("               </select>\r\n");
      out.write("             \r\n");
      out.write("               <input type=\"text\" name=\"username\" id=\"username\" value=\"\" placeholder=\"姓名\"/>\r\n");
      out.write("               <input type=\"text\" name=\"phone\" id=\"phone\"  placeholder=\"联系方式\" />\r\n");
      out.write("               <input type=\"submit\" name=\"tregister\" id=\"tregister\" value=\"注册\" class=\"btnR\" style=\"color: #ffffff;\" />\r\n");
      out.write("             <div><a class=\"RL\" javascript:void(0) onClick=\"showBox2()\">已有账号？去登录</a>\r\n");
      out.write("             </div>\r\n");
      out.write("            </div>\r\n");
      out.write("     </form> \r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("  <div class=\"bg_color\" onClick=\"deleteRegister()\" id=\"bg_filter\" style=\"display: none;\"></div>\r\n");
      out.write("<!-- 登录弹出窗口 -->\r\n");
      out.write("<div class=\"event\" id=\"login_box\" style=\"display: none;\">\r\n");
      out.write("    <div class=\"login\">\r\n");
      out.write("      <div class=\"title\">\r\n");
      out.write("        <img class=\"t_txt\" src=\"images/logo.png\" style=\"width: 200px;height:45px; \">\r\n");
      out.write("        <span class=\"del\" onClick=\"deleteLogin()\">X</span>\r\n");
      out.write("      </div>\r\n");
      out.write("      <form action=\"\" method=\"post\">\r\n");
      out.write("        <input type=\"text\" name=\"\" id=\"\" value=\"\" placeholder=\"请输入用户名\"/>\r\n");
      out.write("        <input type=\"password\" name=\"\" id=\"\" value=\"\" placeholder=\"请输入密码\"/>\r\n");
      out.write("        <input type=\"button\" name=\"\" id=\"\" value=\"登录\" class=\"btnR\" style=\"color: #ffffff;\" />    \r\n");
      out.write("        <div><a class=\"RL\"  javascript:void(0) onClick=\"showBox3()\">还没有账号？去注册</a></div>\r\n");
      out.write("      </form> \r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("  <div class=\"bg_color\" onClick=\"deleteLogin()\" id=\"bg_filter\" style=\"display: none;\"></div>\t\r\n");
      out.write("\t\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005furl_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f0 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    _jspx_th_c_005furl_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005furl_005f0.setParent(null);
    // /photoShow.jsp(38,23) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005furl_005f0.setValue("/ImageServlet");
    int _jspx_eval_c_005furl_005f0 = _jspx_th_c_005furl_005f0.doStartTag();
    if (_jspx_th_c_005furl_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f1 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    _jspx_th_c_005furl_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005furl_005f1.setParent(null);
    // /photoShow.jsp(100,32) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005furl_005f1.setValue("/AlbumServlet");
    int _jspx_eval_c_005furl_005f1 = _jspx_th_c_005furl_005f1.doStartTag();
    if (_jspx_th_c_005furl_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f1);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f1);
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f2 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    _jspx_th_c_005furl_005f2.setPageContext(_jspx_page_context);
    _jspx_th_c_005furl_005f2.setParent(null);
    // /photoShow.jsp(139,38) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005furl_005f2.setValue("/AlbumServlet");
    int _jspx_eval_c_005furl_005f2 = _jspx_th_c_005furl_005f2.doStartTag();
    if (_jspx_th_c_005furl_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f2);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f2);
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fforEach_005f0.setParent(null);
    // /photoShow.jsp(165,17) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setVar("image");
    // /photoShow.jsp(165,17) name = items type = java.lang.Object reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setItems((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${images }", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
    // /photoShow.jsp(165,17) name = varStatus type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fforEach_005f0.setVarStatus("status");
    int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
    try {
      int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
      if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                    <div class=\"album\">\r\n");
          out.write("                        <img onclick = \"showDetail(");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${status.count}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write(")\"  value = ");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${image.image_url }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write(" src=\"");
          if (_jspx_meth_c_005furl_005f3(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
            return true;
          out.write("\">\r\n");
          out.write("                        <input type = \"hidden\" id = \"id_image_url");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${status.count}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\" value = \"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${image.image_url }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\">\r\n");
          out.write("                        <input type = \"hidden\" id = \"image_id");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${status.count}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\" value = \"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${image.id }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\">\r\n");
          out.write("                        <input type = \"hidden\" id = \"album_id\" value = \"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.album.id }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\">\r\n");
          out.write("                        <button  id = \"alert\" type=\"button\" class=\"button gray\" onclick= \"alertOrDelete(");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${status.count}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write(")\">删除</button>  \r\n");
          out.write("                    </div> \r\n");
          out.write("                ");
          int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
    } finally {
      _jspx_th_c_005fforEach_005f0.doFinally();
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f3(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f3 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    _jspx_th_c_005furl_005f3.setPageContext(_jspx_page_context);
    _jspx_th_c_005furl_005f3.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
    // /photoShow.jsp(167,103) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005furl_005f3.setValue((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${image.image_url }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
    int _jspx_eval_c_005furl_005f3 = _jspx_th_c_005furl_005f3.doStartTag();
    if (_jspx_th_c_005furl_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f3);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f3);
    return false;
  }
}
