/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.33
 * Generated at: 2019-02-24 05:11:52 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.Back;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class manageIndex_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/Back/easyui.jsp", Long.valueOf(1491182579156L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
String path=getServletContext().getContextPath(); 
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<!--å¯¼å¥easyuiçç¸å³æä»¶ -->\r\n");
      out.write("<link type=\"text/css\" rel=\"stylesheet\"\r\n");
      out.write("\t\thref=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/jquery-easyui-1.4.2/themes/gray/easyui.css\" />\r\n");
      out.write("<link type=\"text/css\" rel=\"stylesheet\"\r\n");
      out.write("\t\thref=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/jquery-easyui-1.4.2/themes/icon.css\" />\r\n");
      out.write("<script type=\"text/javascript\" \r\n");
      out.write("\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.servletContext.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/jquery-easyui-1.4.2/jquery.min.js\">\t\r\n");
      out.write("</script>\r\n");
      out.write("<script type=\"text/javascript\" \r\n");
      out.write("\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.servletContext.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/jquery-easyui-1.4.2/jquery.easyui.min.js\">\t\r\n");
      out.write("</script>\r\n");
      out.write("<script type=\"text/javascript\" \r\n");
      out.write("\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.servletContext.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/jquery-easyui-1.4.2/locale/easyui-lang-zh_CN.js\">\t\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<title>第四届“和谐*美丽”校园摄影大赛网站后台管理平台</title>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("\t\t#fm{\r\n");
      out.write("\t\t\tmargin:0;\r\n");
      out.write("\t\t\tpadding:10px 30px;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t.ftitle{\r\n");
      out.write("\t\t\tfont-size:14px;\r\n");
      out.write("\t\t\tfont-weight:bold;\r\n");
      out.write("\t\t\tpadding:5px 0;\r\n");
      out.write("\t\t\tmargin-bottom:10px;\r\n");
      out.write("\t\t\tborder-bottom:1px solid #ccc;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t.fitem{\r\n");
      out.write("\t\t\tmargin-bottom:5px;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t.fitem label{\r\n");
      out.write("\t\t\tdisplay:inline-block;\r\n");
      out.write("\t\t\twidth:80px;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t.fitem input{\r\n");
      out.write("\t\t\twidth:160px;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t.fitem select{\r\n");
      out.write("\t\t\twidth:164px;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t</style>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\tfunction addTab(title, url){\r\n");
      out.write("\t\tif ($('#tt').tabs('exists', title)){\r\n");
      out.write("\t\t\t$('#tt').tabs('select', title);\r\n");
      out.write("\t\t} else {\r\n");
      out.write("\t\t\tvar content = '<iframe scrolling=\"auto\" frameborder=\"0\"  src=\"'+url+'\" style=\"width:100%;height:100%;\"></iframe>';\r\n");
      out.write("\t\t\t$('#tt').tabs('add',{\r\n");
      out.write("\t\t\t\ttitle:title,\r\n");
      out.write("\t\t\t\tcontent:content,\r\n");
      out.write("\t\t\t\tclosable:true,\r\n");
      out.write("\t\t\t\tfit:true\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction changePwd(){\r\n");
      out.write("\t    \t$('#dlg2').dialog('open').dialog('setTitle','修改密码');\r\n");
      out.write("\t        url = '");
      out.print(path);
      out.write("/helpManager?status=changePwd&id='+");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${admin.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(";    \r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\tfunction checkNewPwd(opass){\r\n");
      out.write("\t\tif(pwd1.value!=opass){\r\n");
      out.write("\t\t\talert(\"原密码输入错误！\")\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\telse if(pwd2.value!=pwd3.value){\r\n");
      out.write("\t\t\talert(\"两次输入密码不一致！\")\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\telse{\r\n");
      out.write("\t\t\tsavePwd();\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t function savePwd(){\r\n");
      out.write("\t\t$('#fm').form('submit',{\r\n");
      out.write("\t\t\turl: url,\r\n");
      out.write("\t\t\tonSubmit: function(){\r\n");
      out.write("\t\t\t\treturn $(this).form('validate');\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\tsuccess: function(result){\r\n");
      out.write("\t\t\t\tvar r = eval('('+result+')');\r\n");
      out.write("\t\t\t\tif (r[0].errorMsg){\r\n");
      out.write("\t\t\t\t\t$.messager.show({\r\n");
      out.write("\t\t\t\t\t\ttitle: '错误提示',\r\n");
      out.write("\t\t\t\t\t\tmsg: r[0].errorMsg,\r\n");
      out.write("\t\t\t\t\t\ttimeout: 1500\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t$('#dlg2').dialog('close');\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t} \r\n");
      out.write("\t\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\t\r\n");
      out.write("\t<div class=\"easyui-layout\" style=\"width:100%;height:865px;\">\r\n");
      out.write("\t\r\n");
      out.write("<!-- \t\t头部标识 -->\r\n");
      out.write("\t\t<div data-options=\"region:'north'\" style=\"height:87px\">\r\n");
      out.write("\t\t\t<h1 align=\"center\">第四届“和谐*美丽”校园摄影大赛网站后台管理平台</h1>\r\n");
      out.write("\t\t\t<div align=\"right\">\r\n");
      out.write("\t\t\t<p>\r\n");
      out.write("\t\t\t\t<span><a href=\"");
      out.print(path);
      out.write("/Back/manageIndex.jsp\">首页|</a></span>\r\n");
      out.write("\t\t\t\t<span><a href=\"#\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${admin.adminName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("|</a></span>\r\n");
      out.write("\t\t\t\t<!-- <span><a href=\"#\" onclick=\"changePwd()\">修改密码|</a></span> -->\r\n");
      out.write("\t\t\t\t<span><a href=\"");
      out.print(path);
      out.write("/AdminServlet?method=quit\">退出用户</a></span>\r\n");
      out.write("\t\t\t</p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("<!-- \t\t右布局 -->\r\n");
      out.write("<!-- \t\t<div data-options=\"region:'east',split:true\" title=\"East\" style=\"width:200px;\"> -->\r\n");
      out.write("\t\t\r\n");
      out.write("<!-- \t\t</div> -->\r\n");
      out.write("\t\t\r\n");
      out.write("<!-- \t\t左边栏目导航 -->\r\n");
      out.write("\t\t<div data-options=\"region:'west',split:true\" title=\"栏目导航\" style=\"width:200px;\">\r\n");
      out.write("\t\t\t<div class=\"easyui-layout\" data-options=\"fit:true\">\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t<div data-options=\"region:'center',split:true\" style=\"height:550px\">\r\n");
      out.write("\t\t\t\t\t<div class=\"easyui-accordion\" data-options=\"\" >\r\n");
      out.write("\t\t\t\t\t\t<div title=\"作品管理\" style=\"padding:10px;\">\r\n");
      out.write("\t\t\t\t\t\t    <p><a href=\"#\" onclick=\"addTab('相册名称审核','");
      out.print(path);
      out.write("/Back/showAlbum.jsp')\">相册名称审核</a></p>\r\n");
      out.write("\t\t\t\t\t\t    <p><a href=\"#\" onclick=\"addTab('图片审核','");
      out.print(path);
      out.write("/Back/showImage1.jsp')\">图片审核</a></p>\r\n");
      out.write("\t\t\t\t\t\t    <p><a href=\"#\" onclick=\"addTab('所有相册','");
      out.print(path);
      out.write("/Back/showAllAlbum.jsp')\">所有相册</a></p>\r\n");
      out.write("\t\t\t\t\t\t    <p><a href=\"#\" onclick=\"addTab('所有图片','");
      out.print(path);
      out.write("/Back/showAllImage.jsp')\">所有图片</a></p>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<div data-options=\"region:'north',split:true\" >\r\n");
      out.write("\t\t\t\t\t\t<div id=\"pp\" style=\"position:relative\">\r\n");
      out.write("\t\t\t\t\t\t\t<div title=\"Clock\" style=\"text-align:center;background:#f3eeaf;height:110px;padding:5px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<object codebase=\"http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=6,0,29,0\" width=\"100\" height=\"100\" align=\"center\">\r\n");
      out.write("\t\t\t\t\t\t\t      <param name=\"movie\" value=\"http://www.respectsoft.com/onlineclock/analog.swf\">\r\n");
      out.write("\t\t\t\t\t\t\t      <param name=quality value=high>\r\n");
      out.write("\t\t\t\t\t\t\t      <param name=\"wmode\" value=\"transparent\">\r\n");
      out.write("\t\t\t\t\t\t\t      <embed src=\"http://www.respectsoft.com/onlineclock/analog.swf\" width=\"100\" height=\"100\" quality=high pluginspage=\"http://www.macromedia.com/shockwave/download/index.cgi?P1_Prod_Version=ShockwaveFlash\" type=\"application/x-shockwave-flash\" wmode=\"transparent\"></embed>\r\n");
      out.write("\t\t\t\t\t\t\t    </object>\r\n");
      out.write("\t\t\t\t\t\t    </div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("<!-- \t\t中间主要内容 -->\r\n");
      out.write("\t\t<div data-options=\"region:'center',title:'主要内容'\">\r\n");
      out.write("\t\t\t<div id=\"tt\" class=\"easyui-tabs\" data-options=\"fit:true\" \">\r\n");
      out.write("\t\t\t\t<div title=\"Welcome\" style=\"padding:10px\" data-options=\"closable:true\">\r\n");
      out.write("\t\t\t\t\t<h2>尊敬的：");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${admin.adminName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" </h2>\r\n");
      out.write("\t\t\t\t\t<p><h2>&nbsp;&nbsp;欢迎登陆！</h2></p>\r\n");
      out.write("\t\t\t\t</div>\t\t\t\t\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("<!-- \t\t尾部版权申明 -->\r\n");
      out.write("\t\t<div data-options=\"region:'south'\" style=\"height:40px;\" align=\"center\">\r\n");
      out.write("\t\t\t<p>Copyright@2017\tAll Rights Reserved.\t技术支持:<a href=\"http://adou.cnwust.com\">武科大阿豆工作室</a> <a href=\"");
      out.print(path);
      out.write("/index.jsp\">返回前台</a></p>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("<!-- \t\t对话框-->\t\t\r\n");
      out.write("\t\t<div id=\"dlg2\" class=\"easyui-dialog\" style=\"width:350px;height:auto;padding:10px 20px\"\r\n");
      out.write("\t\tclosed=\"true\" buttons=\"#dlg2-buttons\">\r\n");
      out.write("\t\t<div class=\"ftitle\">修改密码</div>\r\n");
      out.write("\t\t<form id=\"fm\" method=\"post\" novalidate>\r\n");
      out.write("\t\t<div class=\"fitem\" id=\"pwd\">\r\n");
      out.write("            <label>原密码:</label>\r\n");
      out.write("            <input id=\"pwd1\" name=\"oldPwd\"  class=\"easyui-textbox\" type=\"password\" required=\"true\">\r\n");
      out.write("        </div>\r\n");
      out.write("\t\t<div class=\"fitem\" id=\"pwd\">\r\n");
      out.write("            <label>新密码:</label>\r\n");
      out.write("            <input id=\"pwd2\" name=\"adminPwd\"  class=\"easyui-textbox\" type=\"password\" required=\"true\">\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"fitem\" id=\"pwdAgain\">\r\n");
      out.write("            <label>确认密码:</label>\r\n");
      out.write("            <input id=\"pwd3\" name=\"adminPwd\" class=\"easyui-textbox\" type=\"password\" validType=\"equalTo['#pwd2']\" required=\"true\">\r\n");
      out.write("        </div>\r\n");
      out.write("        </form>\r\n");
      out.write("     </div>\r\n");
      out.write("<!-- \t\t对话框按钮-->\t     \r\n");
      out.write("     <div id=\"dlg2-buttons\">\r\n");
      out.write("\t    <a href=\"javascript:void(0)\" class=\"easyui-linkbutton\" iconCls=\"icon-ok\" onclick=\"checkNewPwd('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${admin.adminPwd}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("')\" style=\"width:90px\">保存</a>\r\n");
      out.write("\t    <a href=\"javascript:void(0)\" class=\"easyui-linkbutton\" iconCls=\"icon-cancel\" onclick=\"javascript:$('#dlg2').dialog('close')\" style=\"width:90px\">取消</a>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\t\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
