/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.33
 * Generated at: 2019-02-24 05:12:21 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.Back;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class showAllImage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/WEB-INF/lib/standard.jar", Long.valueOf(1491182579116L));
    _jspx_dependants.put("jar:file:/C:/Users/12611/OneDrive/code/eclipse_jee/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/sydsNew6/WEB-INF/lib/standard.jar!/META-INF/c.tld", Long.valueOf(1098682290000L));
    _jspx_dependants.put("/Back/easyui.jsp", Long.valueOf(1491182579156L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
String path=getServletContext().getContextPath();
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(path);
      out.write("/js/jquery-1.11.1.min.js\"></script>\r\n");
      out.write("  <script type=\"text/javascript\" src=\"");
      out.print(path);
      out.write("/js/bootstrap.min.js\"></script> \r\n");
      out.write("  <link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(path);
      out.write("/css/bootstrap.min.css\">\r\n");
      out.write("  <link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(path);
      out.write("/css/carousel.css\">\r\n");
      out.write("  <script type=\"text/javascript\" src=\"");
      out.print(path);
      out.write("/js/carousel.js\"></script> \r\n");
      out.write("  <link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(path);
      out.write("/css/index.css\">\r\n");
      out.write("  <link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(path);
      out.write("/css/style.css\">\r\n");
      out.write("  <script src=\"");
      out.print(path);
      out.write("/js/style.js\" type=\"text/javascript\" charset=\"utf-8\"></script> \r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(path );
      out.write("/js/jquery-1.8.2.js\"></script>\r\n");
      out.write("<!--å¯¼å¥easyuiçç¸å³æä»¶ -->\r\n");
      out.write("<link type=\"text/css\" rel=\"stylesheet\"\r\n");
      out.write("\t\thref=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/jquery-easyui-1.4.2/themes/gray/easyui.css\" />\r\n");
      out.write("<link type=\"text/css\" rel=\"stylesheet\"\r\n");
      out.write("\t\thref=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/jquery-easyui-1.4.2/themes/icon.css\" />\r\n");
      out.write("<script type=\"text/javascript\" \r\n");
      out.write("\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.servletContext.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/jquery-easyui-1.4.2/jquery.min.js\">\t\r\n");
      out.write("</script>\r\n");
      out.write("<script type=\"text/javascript\" \r\n");
      out.write("\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.servletContext.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/jquery-easyui-1.4.2/jquery.easyui.min.js\">\t\r\n");
      out.write("</script>\r\n");
      out.write("<script type=\"text/javascript\" \r\n");
      out.write("\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.servletContext.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/jquery-easyui-1.4.2/locale/easyui-lang-zh_CN.js\">\t\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<title>相册审核</title>\r\n");
      out.write("\r\n");
      out.write("<!-- \tdialog的css -->\r\n");
      out.write("\t<style type=\"text/css\">\r\n");
      out.write("\t\t#fm{\r\n");
      out.write("\t\t\tmargin:0;\r\n");
      out.write("\t\t\tpadding:10px 30px;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t.ftitle{\r\n");
      out.write("\t\t\tfont-size:14px;\r\n");
      out.write("\t\t\tfont-weight:bold;\r\n");
      out.write("\t\t\tpadding:5px 0;\r\n");
      out.write("\t\t\tmargin-bottom:10px;\r\n");
      out.write("\t\t\tborder-bottom:1px solid #ccc;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t.fitem{\r\n");
      out.write("\t\t\tmargin-bottom:5px;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t.fitem label{\r\n");
      out.write("\t\t\tdisplay:inline-block;\r\n");
      out.write("\t\t\twidth:80px;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t.fitem input{\r\n");
      out.write("\t\t\twidth:160px;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t.fitem select{\r\n");
      out.write("\t\t\twidth:164px;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t</style>\r\n");
      out.write("\t\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\t$(function(){\r\n");
      out.write("\t\t$('#dg').datagrid({\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\tfunction downloadImage(){\r\n");
      out.write("\t\tvar row = $('#dg').datagrid('getSelected');\r\n");
      out.write("\t\twindow.location = \"");
      if (_jspx_meth_c_005furl_005f0(_jspx_page_context))
        return;
      out.write("?method=downloadImage&realName=\"+row.realName+\"&phone=\"+row.phone+\"&image_url=\"+row.image_url;\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction queryImage(){\r\n");
      out.write("\t\t$(\"#image_first\").attr(\"src\",\"\");\r\n");
      out.write("\t\tvar row = $('#dg').datagrid('getSelected');\r\n");
      out.write("\t\tvar p = document.getElementById(\"div_imgs\");\r\n");
      out.write("\t\t$(\"#image_first\").attr(\"src\",");
      out.print(path);
      out.write("/+\"\"+row.image_url);\r\n");
      out.write("\t    $(\".photo-mask\").show();\r\n");
      out.write("\t\t$(\".photo-panel\").show();\r\n");
      out.write("\t\timg_src = $(this).attr(\"src\");\r\n");
      out.write("\t\timg_index = $(this).index();\r\n");
      out.write("\t\tphotoView($(this));\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction deleteImage(){\r\n");
      out.write("\t\tvar row = $('#dg').datagrid('getSelected');\r\n");
      out.write("\t    if (row){\r\n");
      out.write("\t    \t$.messager.confirm('删除确认','你确定要删除栏目‘'+row.title+'’吗？',function(r){\r\n");
      out.write("\t            if (r){\r\n");
      out.write("\t                $.post('");
      out.print(path);
      out.write("/AdminServlet?method=deleteImage',{\"id\":row.id,\"album_id\":row.album_id,\"image_url\":row.image_url},function(result){\r\n");
      out.write("\t                    if (result[0].success){\r\n");
      out.write("\t                    \t$('#dg').datagrid('options').url = \"");
      out.print(path);
      out.write("/AdminServlet?method=showAllImages\" ;\r\n");
      out.write("\t                        $('#dg').datagrid('reload');    // reload the user data\r\n");
      out.write("\t                    } else {\r\n");
      out.write("\t                        $.messager.show({    // show error message\r\n");
      out.write("\t                            title: '错误提示',\r\n");
      out.write("\t                            msg: result[0].errorMsg,\r\n");
      out.write("\t                            timeout: 2000\r\n");
      out.write("\t                        });\r\n");
      out.write("\t                    }\r\n");
      out.write("\t                },'json');\r\n");
      out.write("\t            }\r\n");
      out.write("\t        });\r\n");
      out.write("\t    }\r\n");
      out.write("\t    else{\r\n");
      out.write("\t    \t var options = {\r\n");
      out.write("\t    \t            title: \"操作提示\",\r\n");
      out.write("\t    \t            msg: \"请选择您要删除的记录！\",\r\n");
      out.write("\t    \t            showType: 'slide',\r\n");
      out.write("\t    \t            timeout: 1500\r\n");
      out.write("\t    \t        };\r\n");
      out.write("\t    \t $.messager.show(options);\r\n");
      out.write("\t    }\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<!-- \tdatagrid -->\r\n");
      out.write("\t<table id=\"dg\" class=\"easyui-datagrid\" style=\"\" toolbar=\"#toolbar\"\r\n");
      out.write("\t\t\turl=\"");
      out.print(path);
      out.write("/AdminServlet?method=showAllImages\"\r\n");
      out.write("\t\t\tdata-options=\"\r\n");
      out.write("\t\t\t\tlines: true,\r\n");
      out.write("\t\t\t\tidField: 'id',\r\n");
      out.write("\t\t\t\trownumbers:true,\r\n");
      out.write("\t\t \t\tfitColumns:true, \r\n");
      out.write("\t\t \t\tsingleSelect:true,\r\n");
      out.write("\t\t\t\">\r\n");
      out.write("\t\t<thead>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<th field=\"albumName\"  width=\"50\" align=\"center\">相册名称</th>\r\n");
      out.write("\t\t\t\t<!-- <th field=\"image_url\"  width=\"50\" align=\"center\">图片路径</th> -->\r\n");
      out.write("\t\t\t\t<th field=\"realName\"  width=\"50\" align=\"center\">作者</th>\r\n");
      out.write("\t\t\t\t<th field=\"phone\"  width=\"50\" align=\"center\">联系方式</th>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t</thead>\r\n");
      out.write("\t</table>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("<!-- \t操作对话框 -->\r\n");
      out.write("\t<div id=\"dlg\" class=\"easyui-dialog\" style=\"width:400px;height:auto;padding:10px 20px\"\r\n");
      out.write("        closed=\"true\" buttons=\"#dlg-buttons\">\r\n");
      out.write("    <div class=\"ftitle\">所有图片</div>\r\n");
      out.write("    <form id=\"fm\" method=\"post\" novalidate>\r\n");
      out.write("        <div class=\"fitem\">\r\n");
      out.write("            <label>相册名称</label>\r\n");
      out.write("            <input name=\"albumName\" class=\"easyui-textbox\" required=\"true\">\r\n");
      out.write("        </div>\r\n");
      out.write("       <!--  <div class=\"fitem\">\r\n");
      out.write("            <label>图片路径</label>\r\n");
      out.write("            <input name=\"image_url\" class=\"easyui-textbox\" required=\"true\">\r\n");
      out.write("        </div> -->\r\n");
      out.write("        <div class=\"fitem\">\r\n");
      out.write("            <label>作者</label>\r\n");
      out.write("            <input name=\"realName\" class=\"easyui-textbox\" required=\"true\">\r\n");
      out.write("        </div>\r\n");
      out.write("         <div class=\"fitem\">\r\n");
      out.write("            <label>联系方式</label>\r\n");
      out.write("            <input name=\"phone\" class=\"easyui-textbox\" required=\"true\">\r\n");
      out.write("        </div>\r\n");
      out.write("    </form>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- \t操作对话框按钮 -->\r\n");
      out.write("\t<div id=\"dlg-buttons\">\r\n");
      out.write("\t    <a href=\"javascript:void(0)\" class=\"easyui-linkbutton\" iconCls=\"icon-ok\" onclick=\"saveMenu()\" style=\"width:90px\">保存</a>\r\n");
      out.write("\t    <a href=\"javascript:void(0)\" class=\"easyui-linkbutton\" iconCls=\"icon-cancel\" onclick=\"javascript:$('#dlg').dialog('close')\" style=\"width:90px\">取消</a>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<!--     按钮栏 -->\r\n");
      out.write("\t<div id=\"toolbar\" class=\"datagrid-toolbar\">\r\n");
      out.write("\t<a href=\"#\" class=\"easyui-linkbutton\" data-options=\"iconCls:'icon-add'\"plain=\"true\" onclick=\"queryImage()\" >查看详细</a> \t\t\r\n");
      out.write("\t\t<a href=\"#\" class=\"easyui-linkbutton\" data-options=\"iconCls:'icon-cancel'\" plain=\"true\"onclick=\"deleteImage()\">删除</a>\r\n");
      out.write("\t\t<a href=\"#\" class=\"easyui-linkbutton\" data-options=\"iconCls:'icon-add'\"plain=\"true\" onclick=\"downloadImage()\" >下载选中图片</a> \r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- \t右键快捷菜单 -->\r\n");
      out.write("\t<div id=\"mm\" class=\"easyui-menu\" data-options=\"hideOnUnhover:false\"style=\"width:120px;\">\r\n");
      out.write("\t    <div data-options=\"iconCls:'icon-add'\"onclick=\"queryImage()\">查看详细</div>\r\n");
      out.write("\t\t<div data-options=\"iconCls:'icon-cancel'\" onclick=\"deleteImage()\">删除</div>\r\n");
      out.write("\t\t<div data-options=\"iconCls:'icon-add'\"onclick=\"downloadImage()\">下载选中图片</div>\r\n");
      out.write("\t\t<div class=\"menu-sep\"></div>\r\n");
      out.write("\t\t<div>关闭</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- 展示图片 -->\r\n");
      out.write("\t<div id=\"editForm\" class=\"white_content\">\r\n");
      out.write("\t\t<div class=\"imgs\" id=\"div_imgs\"></div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"photo-mask\"></div>\r\n");
      out.write("    <div class=\"photo-panel\">\r\n");
      out.write("      <div class=\"photo-div\">\r\n");
      out.write("        <div class=\"photo-left\">\r\n");
      out.write("          <div class=\"arrow-prv\"></div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"photo-img\">\r\n");
      out.write("          <div class=\"photo-bar\">\r\n");
      out.write("            <div class=\"photo-close\"></div>\r\n");
      out.write("          </div>\r\n");
      out.write("            \r\n");
      out.write("          <div class=\"photo-view-h\">\r\n");
      out.write("\t\t     <img id=\"image_first\" src=\"\" />\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("              \r\n");
      out.write("        <div class=\"photo-right\">\r\n");
      out.write("          <div class=\"arrow-next\"></div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write(" <!-- 展示图片结束 -->\r\n");
      out.write(" \r\n");
      out.write("  <script src=\"js/jquery.min.js\"></script>\r\n");
      out.write("  <script>\r\n");
      out.write("    var img_index = 0;\r\n");
      out.write("    var img_src = \"\";\r\n");
      out.write("    var num=0;\r\n");
      out.write(" //  for(var i=0;i<4;i++){\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    $(function() {\r\n");
      out.write("\t\t//计算居中位置\r\n");
      out.write("\t\tvar mg_top = ((parseInt($(window).height()) - parseInt($(\r\n");
      out.write("\t\t\t\t\".photo-div\").height())) / 2);\r\n");
      out.write("\r\n");
      out.write("\t\t$(\".photo-div\").css({\r\n");
      out.write("\t\t\t\"margin-top\" : \"\" + mg_top + \"px\"\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t//关闭\r\n");
      out.write("\t\t$(\".photo-close\").click(function() {\r\n");
      out.write("\t\t\t$(\".photo-mask\").hide();\r\n");
      out.write("\t\t\t$(\".photo-panel\").hide();\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t//下一张\r\n");
      out.write("\t\t$(\".photo-panel .photo-div .arrow-next\")\r\n");
      out.write("\t\t\t\t.click(\r\n");
      out.write("\t\t\t\t\t\tfunction() {\r\n");
      out.write("\t\t\t\t\t\t\tif (img_index == -1) {\r\n");
      out.write("\t\t\t\t\t\t\t\timg_index = 1;\r\n");
      out.write("\t\t\t\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t\t\t\timg_index++;\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\tif (img_index >= $(\"#editForm .imgs .album img\").length) {\r\n");
      out.write("\t\t\t\t\t\t\t\timg_index = 0;\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\timg_src = $(\"#editForm .imgs .album img\").eq(\r\n");
      out.write("\t\t\t\t\t\t\t\t\timg_index).attr(\"src\");\r\n");
      out.write("\t\t\t\t\t\t\tphotoView($(\"#editForm .imgs .album img\"));\r\n");
      out.write("\t\t\t\t\t\t});\r\n");
      out.write("\t\t//上一张\r\n");
      out.write("\t\t$(\".photo-panel .photo-div .arrow-prv\")\r\n");
      out.write("\t\t\t\t.click(\r\n");
      out.write("\t\t\t\t\t\tfunction() {\r\n");
      out.write("\t\t\t\t\t\t\timg_index--;\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\tif (img_index < 0) {\r\n");
      out.write("\t\t\t\t\t\t\t\timg_index = $(\"#editForm .imgs .album img\").length - 1;\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\timg_src = $(\"#editForm .imgs .album img\").eq(\r\n");
      out.write("\t\t\t\t\t\t\t\t\timg_index).attr(\"src\");\r\n");
      out.write("\t\t\t\t\t\t\tphotoView($(\"#editForm .imgs .album img\"));\r\n");
      out.write("\t\t\t\t\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t//如何调用？展示相册的图片\r\n");
      out.write("\t\t\r\n");
      out.write("\t});\r\n");
      out.write("\r\n");
      out.write("\t//自适应预览\r\n");
      out.write("\tfunction photoView(obj) {\r\n");
      out.write("\t\tif ($(obj).width() >= $(obj).height()) {\r\n");
      out.write("\t\t\t$(\".photo-panel .photo-div .photo-img .photo-view-h\").attr(\r\n");
      out.write("\t\t\t\t\t\"class\", \"photo-view-w\");\r\n");
      out.write("\t\t\t$(\".photo-panel .photo-div .photo-img .photo-view-w img\").attr(\r\n");
      out.write("\t\t\t\t\t\"src\", img_src);\r\n");
      out.write("\t\t} else {\r\n");
      out.write("\t\t\t$(\".photo-panel .photo-div .photo-img .photo-view-w\").attr(\r\n");
      out.write("\t\t\t\t\t\"class\", \"photo-view-h\");\r\n");
      out.write("\t\t\t$(\".photo-panel .photo-div .photo-img .photo-view-h img\").attr(\r\n");
      out.write("\t\t\t\t\t\"src\", img_src);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t//此处写调试日志\r\n");
      out.write("\t\tconsole.log(img_index);\r\n");
      out.write("\t} \r\n");
      out.write("</script>\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\t$(function(){\r\n");
      out.write("\t\t\t$(document).bind('contextmenu',function(e){\r\n");
      out.write("\t\t\t\te.preventDefault();\r\n");
      out.write("\t\t\t\t$('#mm').menu('show', {\r\n");
      out.write("\t\t\t\t\tleft: e.pageX,\r\n");
      out.write("\t\t\t\t\ttop: e.pageY\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t});\r\n");
      out.write("\t</script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005furl_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f0 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    _jspx_th_c_005furl_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005furl_005f0.setParent(null);
    // /Back/showAllImage.jsp(58,21) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005furl_005f0.setValue("/AdminServlet");
    int _jspx_eval_c_005furl_005f0 = _jspx_th_c_005furl_005f0.doStartTag();
    if (_jspx_th_c_005furl_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f0);
    return false;
  }
}
