/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.33
 * Generated at: 2019-02-24 05:11:59 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.Back;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class showAllAlbum_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/Back/easyui.jsp", Long.valueOf(1491182579156L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
String path=getServletContext().getContextPath();
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(path );
      out.write("/js/jquery-1.8.2.js\"></script>\r\n");
      out.write("<!--å¯¼å¥easyuiçç¸å³æä»¶ -->\r\n");
      out.write("<link type=\"text/css\" rel=\"stylesheet\"\r\n");
      out.write("\t\thref=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/jquery-easyui-1.4.2/themes/gray/easyui.css\" />\r\n");
      out.write("<link type=\"text/css\" rel=\"stylesheet\"\r\n");
      out.write("\t\thref=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/jquery-easyui-1.4.2/themes/icon.css\" />\r\n");
      out.write("<script type=\"text/javascript\" \r\n");
      out.write("\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.servletContext.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/jquery-easyui-1.4.2/jquery.min.js\">\t\r\n");
      out.write("</script>\r\n");
      out.write("<script type=\"text/javascript\" \r\n");
      out.write("\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.servletContext.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/jquery-easyui-1.4.2/jquery.easyui.min.js\">\t\r\n");
      out.write("</script>\r\n");
      out.write("<script type=\"text/javascript\" \r\n");
      out.write("\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.servletContext.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/jquery-easyui-1.4.2/locale/easyui-lang-zh_CN.js\">\t\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<title>相册审核</title>\r\n");
      out.write("\r\n");
      out.write("<!-- \tdialog的css -->\r\n");
      out.write("\t<style type=\"text/css\">\r\n");
      out.write("\t\t#fm{\r\n");
      out.write("\t\t\tmargin:0;\r\n");
      out.write("\t\t\tpadding:10px 30px;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t.ftitle{\r\n");
      out.write("\t\t\tfont-size:14px;\r\n");
      out.write("\t\t\tfont-weight:bold;\r\n");
      out.write("\t\t\tpadding:5px 0;\r\n");
      out.write("\t\t\tmargin-bottom:10px;\r\n");
      out.write("\t\t\tborder-bottom:1px solid #ccc;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t.fitem{\r\n");
      out.write("\t\t\tmargin-bottom:5px;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t.fitem label{\r\n");
      out.write("\t\t\tdisplay:inline-block;\r\n");
      out.write("\t\t\twidth:80px;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t.fitem input{\r\n");
      out.write("\t\t\twidth:160px;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t.fitem select{\r\n");
      out.write("\t\t\twidth:164px;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t</style>\r\n");
      out.write("\t\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\t$(function(){\r\n");
      out.write("\t\t$('#dg').datagrid({\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\tfunction queryImage(){\r\n");
      out.write("\t\tvar row = $('#dg').datagrid('getSelected');\r\n");
      out.write("\t\twindow.open(\"");
      out.print(path);
      out.write("/helpManager?status=queryImage&id=\"+row.id)\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\tfunction deleteImage(){\r\n");
      out.write("\t\tvar row = $('#dg').datagrid('getSelected');\r\n");
      out.write("\t    if (row){\r\n");
      out.write("\t    \t$.messager.confirm('删除确认','你确定要删除栏目‘'+row.title+'’吗？',function(r){\r\n");
      out.write("\t            if (r){\r\n");
      out.write("\t                $.post('");
      out.print(path);
      out.write("/AdminServlet?method=deleteAlbum',{\"id\":row.id},function(result){\r\n");
      out.write("\t                    if (result[0].success){\r\n");
      out.write("\t                    \t$('#dg').datagrid('options').url = \"");
      out.print(path);
      out.write("/AdminServlet?method=showAlbums\" ;\r\n");
      out.write("\t                        $('#dg').datagrid('reload');    // reload the user data\r\n");
      out.write("\t                    } else {\r\n");
      out.write("\t                        $.messager.show({    // show error message\r\n");
      out.write("\t                            title: '错误提示',\r\n");
      out.write("\t                            msg: result[0].errorMsg,\r\n");
      out.write("\t                            timeout: 2000\r\n");
      out.write("\t                        });\r\n");
      out.write("\t                    }\r\n");
      out.write("\t                },'json');\r\n");
      out.write("\t            }\r\n");
      out.write("\t        });\r\n");
      out.write("\t    }\r\n");
      out.write("\t    else{\r\n");
      out.write("\t    \t var options = {\r\n");
      out.write("\t    \t            title: \"操作提示\",\r\n");
      out.write("\t    \t            msg: \"请选择您要删除的记录！\",\r\n");
      out.write("\t    \t            showType: 'slide',\r\n");
      out.write("\t    \t            timeout: 1500\r\n");
      out.write("\t    \t        };\r\n");
      out.write("\t    \t $.messager.show(options);\r\n");
      out.write("\t    }\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<!-- \tdatagrid -->\r\n");
      out.write("\t<table id=\"dg\" class=\"easyui-datagrid\" style=\"\" toolbar=\"#toolbar\"\r\n");
      out.write("\t\t\turl=\"");
      out.print(path);
      out.write("/AdminServlet?method=showAllAlbums\"\r\n");
      out.write("\t\t\tdata-options=\"\r\n");
      out.write("\t\t\t\tlines: true,\r\n");
      out.write("\t\t\t\tidField: 'id',\r\n");
      out.write("\t\t\t\trownumbers:true,\r\n");
      out.write("\t\t \t\tfitColumns:true, \r\n");
      out.write("\t\t \t\tsingleSelect:true,\r\n");
      out.write("\t\t\t\">\r\n");
      out.write("\t\t<thead>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<th field=\"albumName\"  width=\"50\" align=\"center\">相册名称</th>\r\n");
      out.write("\t\t\t\t<th field=\"userName\"  width=\"50\" align=\"center\">作者</th>\r\n");
      out.write("\t\t\t\t<th field=\"phone\"  width=\"50\" align=\"center\">联系方式</th>\r\n");
      out.write("\t\t\t\t<th field=\"createTime\" width=\"50\" align=\"center\">日期</th>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t</thead>\r\n");
      out.write("\t</table>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("<!-- \t操作对话框 -->\r\n");
      out.write("\t<div id=\"dlg\" class=\"easyui-dialog\" style=\"width:400px;height:auto;padding:10px 20px\"\r\n");
      out.write("        closed=\"true\" buttons=\"#dlg-buttons\">\r\n");
      out.write("    <div class=\"ftitle\">相册审核</div>\r\n");
      out.write("    <form id=\"fm\" method=\"post\" novalidate>\r\n");
      out.write("        <div class=\"fitem\">\r\n");
      out.write("            <label>相册名称</label>\r\n");
      out.write("            <input name=\"albumName\" class=\"easyui-textbox\" required=\"true\">\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"fitem\">\r\n");
      out.write("            <label>作者</label>\r\n");
      out.write("            <input name=\"userName\" class=\"easyui-textbox\" required=\"true\">\r\n");
      out.write("        </div>\r\n");
      out.write("         <div class=\"fitem\">\r\n");
      out.write("            <label>联系方式</label>\r\n");
      out.write("            <input name=\"phone\" class=\"easyui-textbox\" required=\"true\">\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"fitem\">\r\n");
      out.write("            <label>日期:</label>\r\n");
      out.write("            <input name=\"createTime\" class=\"easyui-textbox\">\r\n");
      out.write("        </div>\r\n");
      out.write("    </form>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- \t操作对话框按钮 -->\r\n");
      out.write("\t<div id=\"dlg-buttons\">\r\n");
      out.write("\t    <a href=\"javascript:void(0)\" class=\"easyui-linkbutton\" iconCls=\"icon-ok\" onclick=\"saveMenu()\" style=\"width:90px\">保存</a>\r\n");
      out.write("\t    <a href=\"javascript:void(0)\" class=\"easyui-linkbutton\" iconCls=\"icon-cancel\" onclick=\"javascript:$('#dlg').dialog('close')\" style=\"width:90px\">取消</a>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<!--     按钮栏 -->\r\n");
      out.write("\t<div id=\"toolbar\" class=\"datagrid-toolbar\">\t\t\r\n");
      out.write("\t\t<a href=\"#\" class=\"easyui-linkbutton\" data-options=\"iconCls:'icon-cancel'\" plain=\"true\"onclick=\"deleteImage()\">删除</a>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- \t右键快捷菜单 -->\r\n");
      out.write("\t<div id=\"mm\" class=\"easyui-menu\" data-options=\"hideOnUnhover:false\"style=\"width:120px;\">\r\n");
      out.write("\t\t<div data-options=\"iconCls:'icon-cancel'\" onclick=\"deleteImage()\">删除</div>\r\n");
      out.write("\t\t<div class=\"menu-sep\"></div>\r\n");
      out.write("\t\t<div>关闭</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\t$(function(){\r\n");
      out.write("\t\t\t$(document).bind('contextmenu',function(e){\r\n");
      out.write("\t\t\t\te.preventDefault();\r\n");
      out.write("\t\t\t\t$('#mm').menu('show', {\r\n");
      out.write("\t\t\t\t\tleft: e.pageX,\r\n");
      out.write("\t\t\t\t\ttop: e.pageY\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t});\r\n");
      out.write("\t</script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
